coverage:
  status:
    project:
      backend:
        flags:
          - backend
        target: auto
        threshold: 1%
    patch:
      backend:
        flags:
          - backend
        target: 90%
        threshold: 0%

flags:
  backend:
    paths:
      - apps/api/
    carryforward: false
