/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/conversations/{id}/inputs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** @description Owner-scoped durable input receipts. Queued inputs expire after 24 hours; receipts are retained for seven days, longer for recoverable Runs. */
        get: operations["listRunInputs"];
        put?: never;
        /** @description Explicit steer or follow_up. Owner derives from authentication. Reusing an idempotency key with changed content returns 409. Steer never modifies frozen policy; follow-up uses a fresh Run. Limits are 8 KiB per input, 16 pending inputs, 64 KiB pending bytes, 64 KiB steering per Run and 256 retained receipts per Conversation. */
        post: operations["enqueueRunInput"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{id}/inputs/{inputID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                inputID: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Withdraw a queued input; applied inputs return 409. Repeated withdrawal is idempotent. */
        delete: operations["withdrawRunInput"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{id}/inputs/start": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Explicitly retry the oldest pending follow-up after completed, failed or canceled execution. Active, waiting and recoverable Runs must be resolved first. Admission is bounded; execution can still fail preparation and leave the receipt queued. */
        post: operations["startFollowup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lists only the current user's owned, granted, non-deleted Workspaces, including archived read-only spaces. Local mode uses a persistent server-owned local User. Selected Workspace headers do not scope this endpoint. */
        get: operations["listWorkspaces"];
        put?: never;
        /** @description Owner is derived from the session, never accepted from the client. IDs are generated by PostgreSQL; names do not identify resources. */
        post: operations["createWorkspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get: operations["getWorkspace"];
        put?: never;
        post?: never;
        /** @description Sets deleted_at. Does not physically erase resource data. Deleted spaces cannot be accessed or implicitly recreated at login. */
        delete: operations["deleteWorkspace"];
        options?: never;
        head?: never;
        /** @description Renames, updates description, archives/restores or selects the default. Closing the current default requires an owned active replacement. Unfinished Runs and uncertain effects block archive/delete. */
        patch: operations["updateWorkspace"];
        trace?: never;
    };
    "/api/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Public session probe. OIDC identity is verified from a revocable cookie;
         *     local mode is explicitly unauthenticated trusted development. Memberships
         *     are database-owned, automatically provisioned for a personal Workspace after
         *     verified login; never supplied by the browser or inferred from email.
         */
        get: operations["getIdentitySession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["startLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description OIDC authorization redirect with prompt=create, state, nonce and S256
         *     PKCE. Available in OIDC mode; a supporting IdP (Keycloak) controls whether
         *     account creation is allowed. Verified login always provisions a personal Workspace.
         *     The IdP receives passwords and owns account creation, policies and MFA.
         */
        get: operations["startRegistration"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["completeLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Revoke the local session and clear its cookie regardless of remaining TTL; requires configured frontend Origin. The next explicit sign-in requests provider reauthentication. Does not end provider SSO or sessions on other devices. Closing a tab does not call this endpoint. */
        post: operations["signOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listConversations"];
        put?: never;
        post: operations["createConversation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteConversation"];
        options?: never;
        head?: never;
        patch: operations["updateConversation"];
        trace?: never;
    };
    "/api/conversations/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        get: operations["listMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["streamChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSkills"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAgents"];
        put?: never;
        post: operations["createAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        get: operations["getAgent"];
        put?: never;
        post?: never;
        delete: operations["archiveAgent"];
        options?: never;
        head?: never;
        patch: operations["updateAgent"];
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/attention": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRunAttention"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/continue": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["continueRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resumeRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get: operations["getRunReplay"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{id}/task-state": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        get: operations["getTaskState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patchTaskState"];
        trace?: never;
    };
    "/api/runs/{id}/projection": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get: operations["getRunProjection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/model_requests": {
        parameters: {
            query?: {
                /** @description Return captured content only when retained by the configured capture policy. */
                include_content?: boolean;
            };
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get: operations["getRunModelRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/episode": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get: operations["getEpisodeReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/tool-effects": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get: operations["listToolEffects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/tool-effects/{idempotency_key}/reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
                idempotency_key: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reconcileToolEffect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/events": {
        parameters: {
            query?: {
                /** @description Resume after this durable Run event sequence. */
                after?: number;
            };
            header?: {
                /** @description SSE resume cursor; takes precedence over the after query parameter. */
                "Last-Event-ID"?: number;
            };
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get: operations["observeRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get: operations["getRunUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/collaboration_steps": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get: operations["listCollaborationSteps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Service-owned Tool catalog with the selected Workspace's persisted grants and effective availability. */
        get: operations["listTools"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tools/{name}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["ToolName"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Allow an installed, service-ready Tool in the selected Workspace. Does not modify operator configuration or Agent selection. */
        post: operations["enableTool"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tools/{name}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["ToolName"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Revoke the selected Workspace's Tool grant. Subsequent execution and recovery callbacks recheck the grant. */
        post: operations["disableTool"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RunInputRequest: {
            /** @enum {string} */
            kind: "steer" | "follow_up";
            run_id: string;
            content: string;
            mode?: components["schemas"]["ChatMode"];
            agent_id?: string;
            idempotency_key: string;
        };
        RunInput: {
            id: string;
            conversation_id: string;
            run_id: string;
            /** @enum {string} */
            kind: "steer" | "follow_up";
            content: string;
            mode: components["schemas"]["ChatMode"];
            agent_id: string;
            /** @enum {string} */
            status: "queued" | "applied" | "withdrawn" | "expired";
            applied_run_id: string;
            stage_id: string;
            turn_id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            applied_at?: string;
        };
        Workspace: {
            /** @description Decimal BIGINT identity encoded as a string to preserve precision. */
            id: string;
            owner_user_id: string;
            name: string;
            description: string;
            /** @enum {string} */
            status: "active" | "archived";
            is_default: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            deleted_at?: string;
        };
        WorkspaceCreateRequest: {
            name: string;
            description?: string;
        };
        WorkspaceUpdateRequest: {
            name?: string;
            description?: string;
            /** @enum {string} */
            status?: "active" | "archived";
            make_default?: boolean;
            replacement_workspace_id?: string;
        };
        IdentityUser: {
            id: string;
            subject: string;
            name: string;
        };
        IdentitySession: {
            /** @enum {string} */
            mode: "local" | "oidc";
            authenticated: boolean;
            /** @description Current owned active default Workspace ID; selection may change, absent when access is revoked. Retained field name for session contract compatibility. */
            personal_workspace?: string;
            user: components["schemas"]["IdentityUser"] | null;
            workspaces: string[];
        };
        ErrorResponse: {
            error: string;
            code?: string;
            source?: string;
            category?: string;
            retryable?: boolean;
            operation?: string;
            request_id?: string;
        };
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
        };
        /** @enum {string} */
        ChatMode: "single" | "multi_agent" | "autonomous";
        /** @enum {string} */
        RunStatus: "queued" | "running" | "waiting_for_user" | "completed" | "failed" | "failed_recoverable" | "canceling" | "canceled";
        /** @enum {string} */
        VerificationStatus: "not_required" | "pending" | "running" | "passed" | "failed" | "blocked" | "stale";
        /** @enum {string} */
        VerifierType: "command" | "http" | "json_schema" | "text_constraints" | "citation" | "answer_relevance" | "grounded_answer";
        VerifierSpecInput: {
            id: string;
            type: components["schemas"]["VerifierType"];
            version?: string;
            required: boolean;
            /** Format: int64 */
            timeout_ms?: number;
            config: {
                [key: string]: unknown;
            };
        };
        VerificationPolicyInput: {
            /** @enum {string} */
            mode: "all_must_pass" | "any_may_pass";
            max_attempts: number;
            /** @enum {string} */
            on_exhausted: "fail" | "waiting_for_user";
        };
        CompletionContractInput: {
            /** @enum {string} */
            subject_type: "run_output";
            verifiers: components["schemas"]["VerifierSpecInput"][];
            policy: components["schemas"]["VerificationPolicyInput"];
        };
        CompletionContract: components["schemas"]["CompletionContractInput"] & {
            id: string;
            version: number;
            hash: string;
        };
        ChatRequest: {
            workspace_id?: string;
            conversation_id?: string;
            agent_id?: string;
            message: string;
            mode?: components["schemas"]["ChatMode"];
            completion_contract?: components["schemas"]["CompletionContractInput"];
        };
        ContinueRunRequest: {
            plan: string;
            routing_requirements?: components["schemas"]["AgentRoutingRequirements"];
        };
        AgentRoutingRequirements: {
            required_tools?: string[];
            prohibited_tools?: string[];
            require_memory?: boolean;
            require_retrieval?: boolean;
            preferred_capabilities?: string[];
        };
        ResumeRunRequest: {
            user_input: string;
        };
        CreateConversationRequest: {
            title: string;
        };
        UpdateConversationRequest: {
            title: string;
        };
        DeleteConversationResponse: {
            deleted: boolean;
        };
        Conversation: {
            id: string;
            workspace_id: string;
            title: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Message: {
            id: string;
            workspace_id: string;
            conversation_id: string;
            /** @enum {string} */
            role: "user" | "assistant" | "system";
            content: string;
            citations?: components["schemas"]["RAGCitation"][];
            web_citations?: components["schemas"]["WebCitation"][];
            /** @description Sanitized completed provider reasoning associated with this assistant answer; display-only, not model input. */
            reasoning?: components["schemas"]["MessageReasoning"][];
            /** Format: date-time */
            created_at: string;
        };
        RAGCitation: {
            source_id: string;
            document_id: string;
            document_title: string;
            document_version?: string;
            chunk_id: string;
            source_chunk_ids?: string[];
            section_path?: string[];
            start_offset?: number;
            end_offset?: number;
            run_id?: string;
            tool_call_id?: string;
            tool_event_id?: string;
        };
        WebCitation: {
            source_id: string;
            title: string;
            /** Format: uri */
            url: string;
            run_id: string;
            tool_call_id: string;
            tool_event_id: string;
        };
        AgentConfigRequest: {
            id?: string;
            name?: string;
            description?: string;
            system_prompt?: string;
            routing_hints?: components["schemas"]["AgentRoutingHints"];
            tools?: string[];
            skills?: string[];
            memory_enabled?: boolean;
            retrieval_enabled?: boolean;
        };
        Agent: {
            /** @description Owning Workspace; absent for shared read-only templates. */
            workspace_id?: string;
            /** @description Shared read-only profile; POST a copy to configure it in a Workspace. */
            is_template?: boolean;
            id: string;
            name: string;
            description: string;
            system_prompt: string;
            routing_hints?: components["schemas"]["AgentRoutingHints"];
            tools: string[];
            skills?: string[];
            memory_enabled: boolean;
            retrieval_enabled: boolean;
            executor?: string;
            archived?: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        SkillMetadata: {
            name: string;
            description: string;
            hash: string;
            required_tools?: string[];
        };
        AgentRoutingHints: {
            capabilities: string[];
            task_examples: string[];
            exclusions: string[];
        };
        ToolInfo: {
            /** @description Operator-owned service switch. Workspace owners cannot override it. */
            service_enabled?: boolean;
            /** @description Persisted Workspace allowlist entry, independent of service readiness. */
            workspace_enabled?: boolean;
            /** Format: int64 */
            config_revision?: number;
            /** @description Service, prerequisite, Workspace or static-policy exclusion reason; argument-dependent decisions remain in Run events. */
            excluded_reason?: string;
            name: string;
            description: string;
            parameters: {
                [key: string]: unknown;
            };
            enabled: boolean;
            /** @description Runtime prerequisite that prevents an enabled Tool from being offered to the model. */
            unavailable_reason?: string;
        };
        Run: {
            id: string;
            workspace_id: string;
            agent_id: string;
            conversation_id: string;
            status: components["schemas"]["RunStatus"];
            verification_status: components["schemas"]["VerificationStatus"];
            completion_contract?: components["schemas"]["CompletionContract"];
            error?: string;
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            execution_started_at?: string;
            /** Format: int64 */
            active_runtime_ms: number;
            /** Format: date-time */
            heartbeat_at?: string;
            /** Format: date-time */
            completed_at?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        OperatorAttentionEvidence: {
            kind: string;
            id?: string;
            status?: string;
            summary: string;
            artifact_refs?: string[];
        };
        OperatorAttentionAction: {
            kind: string;
            label: string;
            enabled: boolean;
            target_id?: string;
            unavailable_reason?: string;
        };
        OperatorAttentionItem: {
            run_id: string;
            conversation_id: string;
            conversation_title: string;
            run_status: components["schemas"]["RunStatus"];
            /** @enum {string} */
            reason: "reconciliation_required" | "recovery_available" | "waiting_for_user" | "verification_attention" | "budget_exhausted" | "failure";
            title: string;
            message: string;
            evidence: components["schemas"]["OperatorAttentionEvidence"][];
            recommended_action?: components["schemas"]["OperatorAttentionAction"];
            /** Format: int64 */
            observation_sequence: number;
            /** Format: date-time */
            updated_at: string;
        };
        CollaborationStep: {
            id: string;
            run_id: string;
            conversation_id: string;
            role: string;
            agent_id?: string;
            status: string;
            iteration?: number;
            input: string;
            output: string;
            error?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        RunEvent: {
            id: string;
            type: string;
            schema_version: number;
            /** Format: int64 */
            sequence: number;
            conversation_id?: string;
            run_id: string;
            stage_id?: string;
            turn_id?: string;
            parent_event_id?: string;
            payload: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            timestamp: string;
        };
        RunTraceSummary: {
            run_id: string;
            status: components["schemas"]["RunStatus"];
            /** Format: int64 */
            total_duration_ms: number;
            total_tokens: number;
            prompt_tokens: number;
            completion_tokens: number;
            token_usage_estimated: boolean;
            llm_calls: number;
            tool_calls: number;
            error_count: number;
        };
        RuntimeRunBudget: {
            max_model_calls?: number;
            max_prompt_tokens?: number;
            max_completion_tokens?: number;
            max_total_tokens?: number;
            max_tool_calls?: number;
            /** Format: int64 */
            max_runtime_ms?: number;
            /** Format: int64 */
            max_estimated_cost_micros?: number;
            /** Format: int64 */
            input_cost_per_million_tokens_micros?: number;
            /** Format: int64 */
            output_cost_per_million_tokens_micros?: number;
        };
        RunUsageTotals: {
            model_calls: number;
            tool_calls: number;
            prompt_tokens: number;
            completion_tokens: number;
            total_tokens: number;
            /** Format: int64 */
            estimated_cost_micros: number;
            open_reservations: number;
            cost_unknown_entries?: number;
        };
        /** @description Optional provider-reported subsets, already included in prompt/completion totals. Absent is unknown, not zero. */
        UsageBreakdown: {
            cached_input_tokens?: number;
            reasoning_tokens?: number;
            /** @enum {string} */
            source: "openai_details" | "deepseek_cache" | "invalid_details";
        };
        UsagePricing: {
            source: string;
            /** Format: int64 */
            input_per_million_tokens_micros: number;
            /** Format: int64 */
            output_per_million_tokens_micros: number;
            /** Format: int64 */
            cached_input_per_million_tokens_micros?: number;
        };
        /** @description Frozen quote and settlement assumptions; an estimate, not a provider invoice. */
        UsageCostDetails: {
            /** @enum {string} */
            status: "estimated" | "unknown";
            reason: string;
            pricing: components["schemas"]["UsagePricing"];
            cache_discount_applied: boolean;
        };
        RunUsageEntry: {
            id: string;
            run_id: string;
            operation_id: string;
            stage_id?: string;
            turn_id?: string;
            /** @enum {string} */
            kind: "model.reservation" | "model.settlement" | "tool.execution";
            /** @enum {string} */
            purpose: "primary" | "router" | "compaction";
            model?: string;
            tool_name?: string;
            model_calls?: number;
            tool_calls?: number;
            prompt_tokens?: number;
            completion_tokens?: number;
            total_tokens?: number;
            /** Format: int64 */
            estimated_cost_micros?: number;
            estimated?: boolean;
            breakdown?: components["schemas"]["UsageBreakdown"];
            cost_details?: components["schemas"]["UsageCostDetails"];
            /** Format: date-time */
            timestamp: string;
        };
        RunUsageLedger: {
            run_id: string;
            budget: components["schemas"]["RuntimeRunBudget"];
            totals: components["schemas"]["RunUsageTotals"];
            entries: components["schemas"]["RunUsageEntry"][] | null;
            /** Format: date-time */
            updated_at?: string;
        };
        VerificationEvidence: {
            id: string;
            run_id: string;
            verifier_id: string;
            status: components["schemas"]["VerificationStatus"];
        } & {
            [key: string]: unknown;
        };
        VerificationArtifact: {
            id: string;
            run_id: string;
            evidence_id: string;
            kind: string;
        } & {
            [key: string]: unknown;
        };
        SkillResourceEvidence: {
            path: string;
            hash: string;
            offset: number;
            next_offset: number;
            total_bytes: number;
            event_id: string;
            /** Format: int64 */
            sequence: number;
        };
        SkillFailureEvidence: {
            tool: string;
            code: string;
            path?: string;
            event_id: string;
            /** Format: int64 */
            sequence: number;
        };
        SkillEvidence: {
            name: string;
            hash: string;
            agent_id: string;
            stage_id?: string;
            bound: boolean;
            /** @enum {string} */
            instructions: "included" | "not_observed";
            /** @enum {string} */
            activation: "explicit" | "model" | "not_observed";
            /** Format: int64 */
            first_sequence?: number;
            /** Format: int64 */
            first_request_sequence?: number;
            manifest_id?: string;
            event_id?: string;
            request_id?: string;
            estimated_tokens?: number;
            resources: components["schemas"]["SkillResourceEvidence"][];
            failures: components["schemas"]["SkillFailureEvidence"][];
        };
        /** @description Bounded display replacement committed at an event sequence; never model continuation or a final Message. */
        PartialOutput: {
            run_id: string;
            stage_id?: string;
            turn_id: string;
            model_call_id?: string;
            attempt?: number;
            round: number;
            /** @enum {string} */
            channel: "answer" | "reasoning";
            role?: string;
            /** Format: int64 */
            revision: number;
            /** @description UTF-8 byte length of this display replacement */
            offset: number;
            text: string;
            /** @enum {string} */
            status: "provisional" | "retracted" | "final" | "interrupted";
            truncated?: boolean;
            /** Format: int64 */
            sequence: number;
        };
        /** @description Bounded semantic progress only; counts do not imply Tool completion. */
        ToolProgressUpdate: {
            phase: string;
            /** @description Backend enforces a 1024 UTF-8 byte cap after redaction. */
            message?: string;
            /** Format: int64 */
            completed?: number;
            /** Format: int64 */
            total?: number;
            truncated?: boolean;
        };
        ToolProgress: components["schemas"]["ToolProgressUpdate"] & {
            run_id: string;
            turn_id: string;
            stage_id?: string;
            tool_call_id: string;
            tool_name: string;
            /** @enum {string} */
            status: "running" | "completed" | "failed" | "interrupted";
            /** Format: int64 */
            sequence: number;
        };
        ToolProgressChunk: {
            /** @constant */
            type: "tool_progress";
            run_id: string;
            turn_id: string;
            stage_id?: string;
            tool_call_id: string;
            tool_name: string;
            /** @enum {string} */
            status: "running" | "completed" | "failed" | "interrupted";
            /** Format: int64 */
            sequence: number;
            update?: components["schemas"]["ToolProgressUpdate"];
        };
        RuntimeInvariantFailure: {
            code: string;
            owner: string;
            run_id: string;
            event_id?: string;
            /** Format: int64 */
            sequence?: number;
            message: string;
        };
        RunProjection: {
            run_id: string;
            conversation_id: string;
            /** @description Durable status; read views tolerate historical values. */
            status: string;
            verification_status: string;
            active_stage_ids: string[] | null;
            active_turn_ids: string[] | null;
            active_model_call_ids: string[] | null;
            active_tool_call_ids: string[] | null;
            summary: components["schemas"]["RunTraceSummary"];
            /** Format: int64 */
            as_of_sequence: number;
        };
        UsageProjection: {
            ledger: components["schemas"]["RunUsageLedger"];
            /** Format: int64 */
            as_of_sequence: number;
        };
        VerificationProjection: {
            status: string;
            latest_attempt: number;
            current_subject_hash?: string;
            evidence_count: number;
            fresh_evidence_count: number;
            /** Format: int64 */
            as_of_sequence: number;
        };
        RunProjectionSnapshot: {
            run: components["schemas"]["RunProjection"];
            usage: components["schemas"]["UsageProjection"];
            verification: components["schemas"]["VerificationProjection"];
            /** Format: int64 */
            as_of_sequence: number;
            invariant_failures: components["schemas"]["RuntimeInvariantFailure"][] | null;
            skill_evidence?: components["schemas"]["SkillEvidence"][];
            partial_outputs: components["schemas"]["PartialOutput"][] | null;
            tool_progress: components["schemas"]["ToolProgress"][] | null;
        };
        RecoveryEvidence: {
            kind: string;
            id?: string;
            status?: string;
            summary: string;
            artifact_refs?: string[];
        };
        RecoveryAction: {
            kind: string;
            label: string;
            enabled: boolean;
            target_id?: string;
            unavailable_reason?: string;
        };
        RecoverySummary: {
            reason: string;
            title: string;
            message: string;
            evidence: components["schemas"]["RecoveryEvidence"][] | null;
            artifact_refs: string[] | null;
            actions: components["schemas"]["RecoveryAction"][] | null;
        };
        /** @enum {string} */
        TaskItemStatus: "pending" | "in_progress" | "completed" | "canceled";
        /** @enum {string} */
        TaskBlockerStatus: "open" | "resolved";
        TaskItem: {
            id: string;
            title: string;
            details?: string;
            status: components["schemas"]["TaskItemStatus"];
            artifact_refs?: string[];
        };
        TaskDecision: {
            id: string;
            statement: string;
            rationale?: string;
            supersedes_id?: string;
        };
        TaskConstraint: {
            id: string;
            statement: string;
        };
        TaskBlocker: {
            id: string;
            description: string;
            status: components["schemas"]["TaskBlockerStatus"];
        };
        TaskState: {
            schema_version: number;
            workspace_id: string;
            conversation_id: string;
            /** Format: int64 */
            version: number;
            goal?: string;
            tasks: components["schemas"]["TaskItem"][];
            decisions: components["schemas"]["TaskDecision"][];
            constraints: components["schemas"]["TaskConstraint"][];
            blockers: components["schemas"]["TaskBlocker"][];
            artifact_refs: string[];
            /** Format: date-time */
            updated_at: string;
        };
        /** @description Closed command names; operation-specific required fields are validated by the domain patch executor. */
        TaskStateOperation: {
            /** @enum {string} */
            type: "set_goal" | "clear_goal" | "upsert_task" | "set_task_status" | "remove_task" | "add_decision" | "upsert_constraint" | "remove_constraint" | "upsert_blocker" | "resolve_blocker" | "remove_blocker" | "add_artifact_ref" | "remove_artifact_ref";
            goal?: string;
            task?: components["schemas"]["TaskItem"];
            task_id?: string;
            task_status?: components["schemas"]["TaskItemStatus"];
            decision?: components["schemas"]["TaskDecision"];
            constraint?: components["schemas"]["TaskConstraint"];
            constraint_id?: string;
            blocker?: components["schemas"]["TaskBlocker"];
            blocker_id?: string;
            artifact_ref?: string;
        };
        TaskStatePatch: {
            /** Format: int64 */
            expected_version: number;
            operations: components["schemas"]["TaskStateOperation"][];
        };
        TaskStateSource: {
            actor_type: string;
            actor_id?: string;
            run_id?: string;
            stage_id?: string;
            turn_id?: string;
            source_message_id?: string;
        };
        TaskStateRevision: {
            id: string;
            workspace_id: string;
            conversation_id: string;
            /** Format: int64 */
            version: number;
            /** Format: int64 */
            previous_version: number;
            patch: components["schemas"]["TaskStatePatch"];
            state: components["schemas"]["TaskState"];
            source: components["schemas"]["TaskStateSource"];
            /** Format: date-time */
            created_at: string;
        };
        ToolArtifact: {
            id: string;
            schema_version: number;
            run_id: string;
            stage_id?: string;
            turn_id?: string;
            tool_call_id: string;
            tool_name: string;
            definition_revision?: string;
            media_type: string;
            content_hash: string;
            original_byte_size: number;
            stored_byte_size: number;
            redacted: boolean;
            redaction_strategy?: string;
            redaction_count: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            expires_at?: string;
            expired?: boolean;
        };
        /** @enum {string} */
        ToolEffectReconciliationAction: "confirm_committed" | "confirm_failed" | "retry_with_same_key" | "compensate";
        ToolEffect: {
            idempotency_key: string;
            /** Format: int64 */
            version: number;
            run_id: string;
            stage_id: string;
            turn_id?: string;
            tool_call_id: string;
            tool_name: string;
            definition_revision?: string;
            request_hash: string;
            status: string;
            has_result: boolean;
            error?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            available_actions?: components["schemas"]["ToolEffectReconciliationAction"][] | null;
        };
        ToolEffectList: {
            run_id: string;
            effects: components["schemas"]["ToolEffect"][];
        };
        ToolEffectReconciliationCommand: {
            command_id: string;
            action: components["schemas"]["ToolEffectReconciliationAction"];
            /** Format: int64 */
            expected_version: number;
            actor: string;
            reason: string;
            result?: unknown;
        };
        ToolEffectReconciliationOutcome: {
            command_id: string;
            applied: boolean;
            outcome: string;
            effect: components["schemas"]["ToolEffect"];
        };
        StageCheckpoint: {
            id: string;
            provider: string;
            run_id: string;
            conversation_id: string;
            stage_id: string;
            status: string;
            input_hash: string;
            output_hash?: string;
            runtime_snapshot_hash: string;
            tool_definitions_hash: string;
            /** Format: int64 */
            event_cursor: number;
            error?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ModelRequestEnvelope: {
            id: string;
            run_id: string;
            conversation_id: string;
            stage_id?: string;
            turn_id?: string;
            model_call_id: string;
            attempt: number;
            operation: string;
            provider: string;
            model: string;
            context_manifest_id?: string;
            runtime_snapshot_hash: string;
            payload_hash: string;
            payload_bytes: number;
            parameters: {
                [key: string]: unknown;
            } | null;
            source_token_breakdown: {
                [key: string]: number;
            } | null;
            message_count: number;
            tool_count: number;
            /** Format: date-time */
            created_at: string;
        };
        ModelRequestCapture: {
            /** @enum {string} */
            mode: "metadata_only" | "redacted" | "full";
            content?: string;
            content_hash?: string;
            original_bytes: number;
            stored_bytes: number;
            redacted: boolean;
            redaction_strategy?: string;
            redaction_count: number;
            truncated: boolean;
            reconstructable: boolean;
            /** Format: date-time */
            expires_at?: string;
            expired: boolean;
        };
        ModelRequestSourceDiff: {
            envelope_selected_tokens: {
                [key: string]: number;
            };
            manifest_selected_tokens: {
                [key: string]: number;
            };
            manifest_excluded_tokens: {
                [key: string]: number;
            };
            matches_envelope: boolean;
        };
        ModelRequestDebugRecord: {
            envelope: components["schemas"]["ModelRequestEnvelope"];
            capture: components["schemas"]["ModelRequestCapture"];
            /** @description Context Manifest metadata */
            manifest?: {
                [key: string]: unknown;
            };
            source_diff: components["schemas"]["ModelRequestSourceDiff"];
        };
        ModelRequestDebugResponse: {
            run_id: string;
            /** @enum {string} */
            reconstructability_status: "valid" | "invalid";
            invariant_error?: string;
            records: components["schemas"]["ModelRequestDebugRecord"][];
        };
        EpisodeRetrievals: {
            event_count: number;
            memories: {
                [key: string]: unknown;
            }[] | null;
            chunks: {
                [key: string]: unknown;
            }[] | null;
        };
        EpisodeLLMCall: {
            event_id: string;
            step_id?: string;
            role?: string;
            agent_id?: string;
            model?: string;
            framework?: string;
            prompt_tokens?: number;
            completion_tokens?: number;
            total_tokens?: number;
            token_usage_estimated?: boolean;
            output_chars?: number;
            /** Format: int64 */
            duration_ms?: number;
        };
        EpisodeToolCall: {
            event_id: string;
            step_id?: string;
            tool_name?: string;
            tool_call_id?: string;
            error?: string;
            /** Format: int64 */
            duration_ms?: number;
        };
        EpisodeError: {
            source: string;
            event_id?: string;
            step_id?: string;
            kind?: string;
            category?: string;
            retryable?: boolean;
            message: string;
        };
        EpisodeVerification: {
            status: string;
            subject_hash?: string;
            contract?: {
                [key: string]: unknown;
            };
            evidence: string[] | null;
            warnings: string[] | null;
            records: components["schemas"]["VerificationEvidence"][] | null;
            artifacts: components["schemas"]["VerificationArtifact"][] | null;
        };
        EpisodeReport: {
            run: components["schemas"]["Run"];
            conversation: components["schemas"]["Conversation"];
            agent: components["schemas"]["Agent"];
            task: string;
            final_output: string;
            messages: components["schemas"]["Message"][] | null;
            steps: components["schemas"]["CollaborationStep"][] | null;
            trace_summary: components["schemas"]["RunTraceSummary"];
            retrievals: components["schemas"]["EpisodeRetrievals"];
            llm_calls: components["schemas"]["EpisodeLLMCall"][] | null;
            tool_calls: components["schemas"]["EpisodeToolCall"][] | null;
            errors: components["schemas"]["EpisodeError"][] | null;
            verification: components["schemas"]["EpisodeVerification"];
        };
        RunReplay: {
            run: components["schemas"]["Run"];
            projection: components["schemas"]["RunProjectionSnapshot"];
            runtime_snapshot?: {
                [key: string]: unknown;
            };
            conversation: components["schemas"]["Conversation"];
            messages: components["schemas"]["Message"][] | null;
            steps: components["schemas"]["CollaborationStep"][] | null;
            summary: components["schemas"]["RunTraceSummary"];
            usage_ledger: components["schemas"]["RunUsageLedger"];
            run_events: components["schemas"]["RunEvent"][] | null;
            stage_checkpoints: components["schemas"]["StageCheckpoint"][] | null;
            tool_effects: components["schemas"]["ToolEffect"][] | null;
            tool_artifacts: components["schemas"]["ToolArtifact"][] | null;
            verification_evidence: components["schemas"]["VerificationEvidence"][] | null;
            verification_artifacts: components["schemas"]["VerificationArtifact"][] | null;
            task_state_revisions: components["schemas"]["TaskStateRevision"][] | null;
            recovery_summary?: components["schemas"]["RecoverySummary"];
        };
        VerificationDecision: {
            status: components["schemas"]["VerificationStatus"];
            allow_completion: boolean;
            attempt: number;
            subject_hash: string;
            run_status: components["schemas"]["RunStatus"];
            summary: string;
        };
        VerifyRunResponse: {
            run: components["schemas"]["Run"];
            decision: components["schemas"]["VerificationDecision"];
        };
        ConversationChunk: {
            /** @constant */
            type: "conversation";
            conversation_id: string;
        };
        RunStateChunk: {
            /** @constant */
            type: "run_state";
            conversation_id: string;
            run_id: string;
            agent_id: string;
            status: components["schemas"]["RunStatus"];
        };
        RunProgressChunk: {
            /** @constant */
            type: "run_progress";
            conversation_id: string;
            run_id: string;
            agent_id?: string;
            iteration?: number;
            max_iterations?: number;
            elapsed_seconds?: number;
            max_runtime_seconds?: number;
            output_chars?: number;
            max_output_chars?: number;
            tool_calls?: number;
            max_tool_calls?: number;
            stop_reason?: string;
        };
        ModelDeltaChunk: {
            /** @constant */
            type: "model_delta";
            delta: string;
            /** @description Clear the current assistant draft before appending delta; retracts provisional text when a streamed round chooses tools. */
            reset?: boolean;
        };
        MessageReasoning: {
            run_id: string;
            turn_id: string;
            stage_id?: string;
            model_call_id: string;
            /** @enum {string} */
            format: "deepseek_reasoning_content";
            /** @constant */
            status: "complete";
            /** @description Redacted plain text */
            text?: string;
            truncated?: boolean;
        };
        /** @description Sanitized provider output, never an answer or private continuation. Completed text is durable; live text replaces this call's display copy. */
        ModelReasoningChunk: {
            /** @constant */
            type: "model_reasoning";
            run_id: string;
            turn_id: string;
            stage_id?: string;
            model_call_id: string;
            /** @enum {string} */
            format: "deepseek_reasoning_content";
            /** @enum {string} */
            status: "receiving" | "complete" | "interrupted";
            /** @description Redacted plain-text replacement, at most 16 KiB UTF-8. Receiving text is an ephemeral safe prefix; complete text is durable. Interrupted events contain no text. */
            text?: string;
            truncated?: boolean;
        };
        StageStateChunk: {
            /** @constant */
            type: "stage_state";
            conversation_id: string;
            run_id: string;
            agent_id?: string;
            role: string;
            status: string;
            iteration?: number;
            input?: string;
            output?: string;
            error?: string;
        };
        DoneChunk: {
            /** @constant */
            type: "done";
            conversation_id: string;
            title?: string;
            message_id?: string;
            run_id?: string;
            agent_id?: string;
            status?: components["schemas"]["RunStatus"];
            verification_status?: components["schemas"]["VerificationStatus"];
            citations?: components["schemas"]["RAGCitation"][];
            invalid_citation_ids?: string[];
            web_citations?: components["schemas"]["WebCitation"][];
            invalid_web_citation_ids?: string[];
        };
        ErrorChunk: {
            /** @constant */
            type: "error";
            error: string;
            code?: string;
            source?: string;
            category?: string;
            retryable?: boolean;
            /** Format: int64 */
            retry_after_ms?: number;
            request_id?: string;
        };
        ChatStreamEvent: components["schemas"]["ConversationChunk"] | components["schemas"]["RunStateChunk"] | components["schemas"]["RunProgressChunk"] | components["schemas"]["ModelDeltaChunk"] | components["schemas"]["ModelReasoningChunk"] | components["schemas"]["ToolProgressChunk"] | components["schemas"]["StageStateChunk"] | components["schemas"]["DoneChunk"] | components["schemas"]["ErrorChunk"] | components["schemas"]["RunEvent"];
    };
    responses: {
        /** @description Invalid request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Requested resource was not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Request conflicts with current resource state. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Run admission queue is full or temporarily unavailable. */
        TooManyRequests: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Internal server error. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        ConversationId: string;
        AgentId: string;
        RunId: string;
        ToolName: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listRunInputs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Input receipts in submission order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunInput"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    enqueueRunInput: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunInputRequest"];
            };
        };
        responses: {
            /** @description Durable receipt; applied does not mean model compliance. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunInput"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["BadRequest"];
            429: components["responses"]["BadRequest"];
        };
    };
    withdrawRunInput: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                inputID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Withdrawn receipt. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunInput"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["BadRequest"];
        };
    };
    startFollowup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dispatcher admitted; consult the durable receipt for Run creation. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status: string;
                    };
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["BadRequest"];
            429: components["responses"]["BadRequest"];
        };
    };
    listWorkspaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Owned Workspaces. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"][];
                };
            };
        };
    };
    createWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceCreateRequest"];
            };
        };
        responses: {
            /** @description Created Workspace. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Owned and granted Workspace. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteWorkspace: {
        parameters: {
            query?: {
                replacement_workspace_id?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Soft-deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            /** @description Workspace cannot currently be deleted. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceUpdateRequest"];
            };
        };
        responses: {
            /** @description Updated Workspace, preserving its ID. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Last active space, invalid replacement default, unfinished Run or uncertain effect prevents the change. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getIdentitySession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current authentication mode, identity and Workspace memberships. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentitySession"];
                };
            };
            /** @description Identity persistence unavailable; no local-mode fallback. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    startLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OIDC authorization redirect with state, nonce, S256 PKCE and prompt=login to require fresh authentication. */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    startRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to the IdP registration screen. */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            /** @description Cannot persist the authorization attempt. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    completeLogin: {
        parameters: {
            query?: {
                code?: string;
                state?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verified OIDC login ensures an idempotent personal Workspace before creating a host-only HttpOnly session and redirecting to the workbench. Revoked Memberships are not restored. */
            303: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            /** @description Invalid identity token or nonce. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Identity persistence or personal Workspace provisioning failed; no session is issued. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    signOut: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Local session revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Mutation Origin rejected. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API process health. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listConversations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversations visible in the current workspace. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    createConversation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConversationRequest"];
            };
        };
        responses: {
            /** @description Created conversation. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversation deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteConversationResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updateConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateConversationRequest"];
            };
        };
        responses: {
            /** @description Updated conversation. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listMessages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversation messages. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"][];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    streamChat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Server-sent stream of ChatStreamEvent values. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    listSkills: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operator-trusted Skill metadata, without directory paths or contents. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillMetadata"][];
                };
            };
        };
    };
    listAgents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active agents. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    createAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentConfigRequest"];
            };
        };
        responses: {
            /** @description Created agent. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent configuration. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    archiveAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent archived. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    updateAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentConfigRequest"];
            };
        };
        responses: {
            /** @description Updated agent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listRuns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runs ordered by the store. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listRunAttention: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Highest-priority operator attention item for each actionable Run. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperatorAttentionItem"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    continueRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContinueRunRequest"];
            };
        };
        responses: {
            /** @description Server-sent stream of ChatStreamEvent values. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    resumeRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeRunRequest"];
            };
        };
        responses: {
            /** @description Server-sent stream of ChatStreamEvent values. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    cancelRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Canceled or canceling run. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    verifyRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verification decision and resulting Run state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyRunResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    getRunReplay: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Replayable Run state and evidence. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunReplay"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getTaskState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current structured state; empty collections when no revision exists. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskState"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    patchTaskState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskStatePatch"];
            };
        };
        responses: {
            /** @description Immutable applied revision. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskStateRevision"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    getRunProjection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event-derived read models and runtime diagnostics at an event watermark. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunProjectionSnapshot"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getRunModelRequests: {
        parameters: {
            query?: {
                /** @description Return captured content only when retained by the configured capture policy. */
                include_content?: boolean;
            };
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Physical request metadata, policy-controlled capture and source accounting. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelRequestDebugResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getEpisodeReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Derived episode report; not an independent source of Run state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodeReport"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listToolEffects: {
        parameters: {
            query?: {
                status?: string;
                tool?: string;
            };
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Effect summaries without raw result content. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolEffectList"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    reconcileToolEffect: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
                idempotency_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToolEffectReconciliationCommand"];
            };
        };
        responses: {
            /** @description Idempotent reconciliation outcome. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolEffectReconciliationOutcome"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    observeRunEvents: {
        parameters: {
            query?: {
                /** @description Resume after this durable Run event sequence. */
                after?: number;
            };
            header?: {
                /** @description SSE resume cursor; takes precedence over the after query parameter. */
                "Last-Event-ID"?: number;
            };
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Snapshot, durable event replay, and live Run events as server-sent events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    getRunUsage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run budget and append-only usage ledger. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunUsageLedger"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listCollaborationSteps: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Multi-Agent or Autonomous stages for the Run. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollaborationStep"][];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listTools: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tool catalog, Workspace configuration revision and exclusion reasons. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolInfo"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    enableTool: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["ToolName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated tool catalog. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolInfo"][];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    disableTool: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["ToolName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated tool catalog. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolInfo"][];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
}
