/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lists only the current user's owned, granted, non-deleted Workspaces, including archived read-only spaces. Local mode uses a persistent server-owned local User. Selected Workspace headers do not scope this endpoint. */
        get: operations["listWorkspaces"];
        put?: never;
        /** @description Owner is derived from the session, never accepted from the client. IDs are generated by PostgreSQL; names do not identify resources. */
        post: operations["createWorkspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get: operations["getWorkspace"];
        put?: never;
        post?: never;
        /** @description Sets deleted_at. Does not physically erase resource data. Deleted spaces cannot be accessed or implicitly recreated at login. */
        delete: operations["deleteWorkspace"];
        options?: never;
        head?: never;
        /** @description Renames, updates description, archives/restores or selects the default. Closing the current default requires an owned active replacement. Unfinished Runs and uncertain effects block archive/delete. */
        patch: operations["updateWorkspace"];
        trace?: never;
    };
    "/api/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Public session probe. OIDC identity is verified from a revocable cookie;
         *     local mode is explicitly unauthenticated trusted development. Memberships
         *     are database-owned, automatically provisioned for a personal Workspace after
         *     verified login; never supplied by the browser or inferred from email.
         */
        get: operations["getIdentitySession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["startLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description OIDC authorization redirect with prompt=create, state, nonce and S256
         *     PKCE. Available in OIDC mode; a supporting IdP (Keycloak) controls whether
         *     account creation is allowed. Verified login always provisions a personal Workspace.
         *     The IdP receives passwords and owns account creation, policies and MFA.
         */
        get: operations["startRegistration"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["completeLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Revoke the local session and clear its cookie regardless of remaining TTL; requires configured frontend Origin. The next explicit sign-in requests provider reauthentication. Does not end provider SSO or sessions on other devices. Closing a tab does not call this endpoint. */
        post: operations["signOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listConversations"];
        put?: never;
        post: operations["createConversation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteConversation"];
        options?: never;
        head?: never;
        patch: operations["updateConversation"];
        trace?: never;
    };
    "/api/conversations/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        get: operations["listMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["streamChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSkills"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAgents"];
        put?: never;
        post: operations["createAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        get: operations["getAgent"];
        put?: never;
        post?: never;
        delete: operations["archiveAgent"];
        options?: never;
        head?: never;
        patch: operations["updateAgent"];
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/attention": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRunAttention"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/continue": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["continueRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resumeRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get: operations["getRunReplay"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/events": {
        parameters: {
            query?: {
                /** @description Resume after this durable Run event sequence. */
                after?: number;
            };
            header?: {
                /** @description SSE resume cursor; takes precedence over the after query parameter. */
                "Last-Event-ID"?: number;
            };
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get: operations["observeRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get: operations["getRunUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/collaboration_steps": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get: operations["listCollaborationSteps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTools"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tools/{name}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["ToolName"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["enableTool"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tools/{name}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["ToolName"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["disableTool"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Workspace: {
            /** @description Decimal BIGINT identity encoded as a string to preserve precision. */
            id: string;
            owner_user_id: string;
            name: string;
            description: string;
            /** @enum {string} */
            status: "active" | "archived";
            is_default: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            deleted_at?: string;
        };
        WorkspaceCreateRequest: {
            name: string;
            description?: string;
        };
        WorkspaceUpdateRequest: {
            name?: string;
            description?: string;
            /** @enum {string} */
            status?: "active" | "archived";
            make_default?: boolean;
            replacement_workspace_id?: string;
        };
        IdentityUser: {
            id: string;
            subject: string;
            name: string;
        };
        IdentitySession: {
            /** @enum {string} */
            mode: "local" | "oidc";
            authenticated: boolean;
            /** @description Current owned active default Workspace ID; selection may change, absent when access is revoked. Retained field name for session contract compatibility. */
            personal_workspace?: string;
            user: components["schemas"]["IdentityUser"] | null;
            workspaces: string[];
        };
        ErrorResponse: {
            error: string;
            code?: string;
            source?: string;
            category?: string;
            retryable?: boolean;
            operation?: string;
            request_id?: string;
        };
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
        };
        /** @enum {string} */
        ChatMode: "single" | "multi_agent" | "autonomous";
        /** @enum {string} */
        RunStatus: "queued" | "running" | "waiting_for_user" | "completed" | "failed" | "failed_recoverable" | "canceling" | "canceled";
        /** @enum {string} */
        VerificationStatus: "not_required" | "pending" | "running" | "passed" | "failed" | "blocked" | "stale";
        /** @enum {string} */
        VerifierType: "command" | "http" | "json_schema" | "text_constraints" | "citation" | "answer_relevance" | "grounded_answer";
        VerifierSpecInput: {
            id: string;
            type: components["schemas"]["VerifierType"];
            version?: string;
            required: boolean;
            /** Format: int64 */
            timeout_ms?: number;
            config: {
                [key: string]: unknown;
            };
        };
        VerificationPolicyInput: {
            /** @enum {string} */
            mode: "all_must_pass" | "any_may_pass";
            max_attempts: number;
            /** @enum {string} */
            on_exhausted: "fail" | "waiting_for_user";
        };
        CompletionContractInput: {
            /** @enum {string} */
            subject_type: "run_output";
            verifiers: components["schemas"]["VerifierSpecInput"][];
            policy: components["schemas"]["VerificationPolicyInput"];
        };
        CompletionContract: components["schemas"]["CompletionContractInput"] & {
            id: string;
            version: number;
            hash: string;
        };
        ChatRequest: {
            workspace_id?: string;
            conversation_id?: string;
            agent_id?: string;
            message: string;
            mode?: components["schemas"]["ChatMode"];
            completion_contract?: components["schemas"]["CompletionContractInput"];
        };
        ContinueRunRequest: {
            plan: string;
            routing_requirements?: components["schemas"]["AgentRoutingRequirements"];
        };
        AgentRoutingRequirements: {
            required_tools?: string[];
            prohibited_tools?: string[];
            require_memory?: boolean;
            require_retrieval?: boolean;
            preferred_capabilities?: string[];
        };
        ResumeRunRequest: {
            user_input: string;
        };
        CreateConversationRequest: {
            title: string;
        };
        UpdateConversationRequest: {
            title: string;
        };
        DeleteConversationResponse: {
            deleted: boolean;
        };
        Conversation: {
            id: string;
            workspace_id: string;
            title: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Message: {
            id: string;
            workspace_id: string;
            conversation_id: string;
            /** @enum {string} */
            role: "user" | "assistant" | "system";
            content: string;
            citations?: components["schemas"]["RAGCitation"][];
            web_citations?: components["schemas"]["WebCitation"][];
            /** @description Sanitized completed provider reasoning associated with this assistant answer; display-only, not model input. */
            reasoning?: components["schemas"]["MessageReasoning"][];
            /** Format: date-time */
            created_at: string;
        };
        RAGCitation: {
            source_id: string;
            document_id: string;
            document_title: string;
            document_version?: string;
            chunk_id: string;
            source_chunk_ids?: string[];
            section_path?: string[];
            start_offset?: number;
            end_offset?: number;
            run_id?: string;
            tool_call_id?: string;
            tool_event_id?: string;
        };
        WebCitation: {
            source_id: string;
            title: string;
            /** Format: uri */
            url: string;
            run_id: string;
            tool_call_id: string;
            tool_event_id: string;
        };
        AgentConfigRequest: {
            id?: string;
            name?: string;
            description?: string;
            system_prompt?: string;
            routing_hints?: components["schemas"]["AgentRoutingHints"];
            tools?: string[];
            skills?: string[];
            memory_enabled?: boolean;
            retrieval_enabled?: boolean;
        };
        Agent: {
            id: string;
            name: string;
            description: string;
            system_prompt: string;
            routing_hints?: components["schemas"]["AgentRoutingHints"];
            tools: string[];
            skills?: string[];
            memory_enabled: boolean;
            retrieval_enabled: boolean;
            executor?: string;
            archived?: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        SkillMetadata: {
            name: string;
            description: string;
            hash: string;
            required_tools?: string[];
        };
        AgentRoutingHints: {
            capabilities: string[];
            task_examples: string[];
            exclusions: string[];
        };
        ToolInfo: {
            name: string;
            description: string;
            parameters: {
                [key: string]: unknown;
            };
            enabled: boolean;
            /** @description Runtime prerequisite that prevents an enabled Tool from being offered to the model. */
            unavailable_reason?: string;
        };
        Run: {
            id: string;
            workspace_id: string;
            agent_id: string;
            conversation_id: string;
            status: components["schemas"]["RunStatus"];
            verification_status: components["schemas"]["VerificationStatus"];
            completion_contract?: components["schemas"]["CompletionContract"];
            error?: string;
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            execution_started_at?: string;
            /** Format: int64 */
            active_runtime_ms: number;
            /** Format: date-time */
            heartbeat_at?: string;
            /** Format: date-time */
            completed_at?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        OperatorAttentionEvidence: {
            kind: string;
            id?: string;
            status?: string;
            summary: string;
            artifact_refs?: string[];
        };
        OperatorAttentionAction: {
            kind: string;
            label: string;
            enabled: boolean;
            target_id?: string;
            unavailable_reason?: string;
        };
        OperatorAttentionItem: {
            run_id: string;
            conversation_id: string;
            conversation_title: string;
            run_status: components["schemas"]["RunStatus"];
            /** @enum {string} */
            reason: "reconciliation_required" | "recovery_available" | "waiting_for_user" | "verification_attention" | "budget_exhausted" | "failure";
            title: string;
            message: string;
            evidence: components["schemas"]["OperatorAttentionEvidence"][];
            recommended_action?: components["schemas"]["OperatorAttentionAction"];
            /** Format: int64 */
            observation_sequence: number;
            /** Format: date-time */
            updated_at: string;
        };
        CollaborationStep: {
            id: string;
            run_id: string;
            conversation_id: string;
            role: string;
            agent_id?: string;
            status: string;
            iteration?: number;
            input: string;
            output: string;
            error?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        RunEvent: {
            id: string;
            type: string;
            schema_version: number;
            /** Format: int64 */
            sequence: number;
            conversation_id?: string;
            run_id: string;
            stage_id?: string;
            turn_id?: string;
            parent_event_id?: string;
            payload: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            timestamp: string;
        };
        RunTraceSummary: {
            run_id: string;
            status: components["schemas"]["RunStatus"];
            /** Format: int64 */
            total_duration_ms: number;
            total_tokens: number;
            prompt_tokens: number;
            completion_tokens: number;
            token_usage_estimated: boolean;
            llm_calls: number;
            tool_calls: number;
            error_count: number;
        };
        RuntimeRunBudget: {
            max_model_calls?: number;
            max_prompt_tokens?: number;
            max_completion_tokens?: number;
            max_total_tokens?: number;
            max_tool_calls?: number;
            /** Format: int64 */
            max_runtime_ms?: number;
            /** Format: int64 */
            max_estimated_cost_micros?: number;
            /** Format: int64 */
            input_cost_per_million_tokens_micros?: number;
            /** Format: int64 */
            output_cost_per_million_tokens_micros?: number;
        };
        RunUsageTotals: {
            model_calls: number;
            tool_calls: number;
            prompt_tokens: number;
            completion_tokens: number;
            total_tokens: number;
            /** Format: int64 */
            estimated_cost_micros: number;
            open_reservations: number;
            cost_unknown_entries?: number;
        };
        /** @description Optional provider-reported subsets, already included in prompt/completion totals. Absent is unknown, not zero. */
        UsageBreakdown: {
            cached_input_tokens?: number;
            reasoning_tokens?: number;
            /** @enum {string} */
            source: "openai_details" | "deepseek_cache" | "invalid_details";
        };
        UsagePricing: {
            source: string;
            /** Format: int64 */
            input_per_million_tokens_micros: number;
            /** Format: int64 */
            output_per_million_tokens_micros: number;
            /** Format: int64 */
            cached_input_per_million_tokens_micros?: number;
        };
        /** @description Frozen quote and settlement assumptions; an estimate, not a provider invoice. */
        UsageCostDetails: {
            /** @enum {string} */
            status: "estimated" | "unknown";
            reason: string;
            pricing: components["schemas"]["UsagePricing"];
            cache_discount_applied: boolean;
        };
        RunUsageEntry: {
            id: string;
            run_id: string;
            operation_id: string;
            stage_id?: string;
            turn_id?: string;
            /** @enum {string} */
            kind: "model.reservation" | "model.settlement" | "tool.execution";
            /** @enum {string} */
            purpose: "primary" | "router" | "compaction";
            model?: string;
            tool_name?: string;
            model_calls?: number;
            tool_calls?: number;
            prompt_tokens?: number;
            completion_tokens?: number;
            total_tokens?: number;
            /** Format: int64 */
            estimated_cost_micros?: number;
            estimated?: boolean;
            breakdown?: components["schemas"]["UsageBreakdown"];
            cost_details?: components["schemas"]["UsageCostDetails"];
            /** Format: date-time */
            timestamp: string;
        };
        RunUsageLedger: {
            run_id: string;
            budget: components["schemas"]["RuntimeRunBudget"];
            totals: components["schemas"]["RunUsageTotals"];
            entries: components["schemas"]["RunUsageEntry"][];
            /** Format: date-time */
            updated_at?: string;
        };
        VerificationEvidence: {
            id: string;
            run_id: string;
            verifier_id: string;
            status: components["schemas"]["VerificationStatus"];
        } & {
            [key: string]: unknown;
        };
        VerificationArtifact: {
            id: string;
            run_id: string;
            evidence_id: string;
            kind: string;
        } & {
            [key: string]: unknown;
        };
        SkillResourceEvidence: {
            path: string;
            hash: string;
            offset: number;
            next_offset: number;
            total_bytes: number;
            event_id: string;
            /** Format: int64 */
            sequence: number;
        };
        SkillFailureEvidence: {
            tool: string;
            code: string;
            path?: string;
            event_id: string;
            /** Format: int64 */
            sequence: number;
        };
        SkillEvidence: {
            name: string;
            hash: string;
            agent_id: string;
            stage_id?: string;
            bound: boolean;
            /** @enum {string} */
            instructions: "included" | "not_observed";
            /** @enum {string} */
            activation: "explicit" | "model" | "not_observed";
            /** Format: int64 */
            first_sequence?: number;
            /** Format: int64 */
            first_request_sequence?: number;
            manifest_id?: string;
            event_id?: string;
            request_id?: string;
            estimated_tokens?: number;
            resources: components["schemas"]["SkillResourceEvidence"][];
            failures: components["schemas"]["SkillFailureEvidence"][];
        };
        /** @description Bounded display replacement committed at an event sequence; never model continuation or a final Message. */
        PartialOutput: {
            run_id: string;
            stage_id?: string;
            turn_id: string;
            model_call_id?: string;
            attempt?: number;
            round: number;
            /** @enum {string} */
            channel: "answer" | "reasoning";
            role?: string;
            /** Format: int64 */
            revision: number;
            /** @description UTF-8 byte length of this display replacement */
            offset: number;
            text: string;
            /** @enum {string} */
            status: "provisional" | "retracted" | "final" | "interrupted";
            truncated?: boolean;
            /** Format: int64 */
            sequence: number;
        };
        RunReplay: {
            run: components["schemas"]["Run"];
            projection: {
                skill_evidence?: components["schemas"]["SkillEvidence"][];
                partial_outputs?: components["schemas"]["PartialOutput"][];
            } & {
                [key: string]: unknown;
            };
            runtime_snapshot?: {
                [key: string]: unknown;
            };
            conversation: components["schemas"]["Conversation"];
            messages: components["schemas"]["Message"][];
            steps: components["schemas"]["CollaborationStep"][];
            summary: components["schemas"]["RunTraceSummary"];
            usage_ledger: components["schemas"]["RunUsageLedger"];
            run_events: components["schemas"]["RunEvent"][];
            stage_checkpoints: {
                [key: string]: unknown;
            }[];
            tool_effects: {
                [key: string]: unknown;
            }[];
            tool_artifacts: {
                [key: string]: unknown;
            }[];
            verification_evidence: components["schemas"]["VerificationEvidence"][];
            verification_artifacts: components["schemas"]["VerificationArtifact"][];
            task_state_revisions: {
                [key: string]: unknown;
            }[];
            recovery_summary?: {
                [key: string]: unknown;
            };
        };
        VerificationDecision: {
            status: components["schemas"]["VerificationStatus"];
            allow_completion: boolean;
            attempt: number;
            subject_hash: string;
            run_status: components["schemas"]["RunStatus"];
            summary: string;
        };
        VerifyRunResponse: {
            run: components["schemas"]["Run"];
            decision: components["schemas"]["VerificationDecision"];
        };
        ConversationChunk: {
            /** @constant */
            type: "conversation";
            conversation_id: string;
        };
        RunStateChunk: {
            /** @constant */
            type: "run_state";
            conversation_id: string;
            run_id: string;
            agent_id: string;
            status: components["schemas"]["RunStatus"];
        };
        RunProgressChunk: {
            /** @constant */
            type: "run_progress";
            conversation_id: string;
            run_id: string;
            agent_id?: string;
            iteration?: number;
            max_iterations?: number;
            elapsed_seconds?: number;
            max_runtime_seconds?: number;
            output_chars?: number;
            max_output_chars?: number;
            tool_calls?: number;
            max_tool_calls?: number;
            stop_reason?: string;
        };
        ModelDeltaChunk: {
            /** @constant */
            type: "model_delta";
            delta: string;
            /** @description Clear the current assistant draft before appending delta; retracts provisional text when a streamed round chooses tools. */
            reset?: boolean;
        };
        MessageReasoning: {
            run_id: string;
            turn_id: string;
            stage_id?: string;
            model_call_id: string;
            /** @enum {string} */
            format: "deepseek_reasoning_content";
            /** @constant */
            status: "complete";
            /** @description Redacted plain text */
            text?: string;
            truncated?: boolean;
        };
        /** @description Sanitized provider output, never an answer or private continuation. Completed text is durable; live text replaces this call's display copy. */
        ModelReasoningChunk: {
            /** @constant */
            type: "model_reasoning";
            run_id: string;
            turn_id: string;
            stage_id?: string;
            model_call_id: string;
            /** @enum {string} */
            format: "deepseek_reasoning_content";
            /** @enum {string} */
            status: "receiving" | "complete" | "interrupted";
            /** @description Redacted plain-text replacement, at most 16 KiB UTF-8. Receiving text is an ephemeral safe prefix; complete text is durable. Interrupted events contain no text. */
            text?: string;
            truncated?: boolean;
        };
        StageStateChunk: {
            /** @constant */
            type: "stage_state";
            conversation_id: string;
            run_id: string;
            agent_id?: string;
            role: string;
            status: string;
            iteration?: number;
            input?: string;
            output?: string;
            error?: string;
        };
        DoneChunk: {
            /** @constant */
            type: "done";
            conversation_id: string;
            title?: string;
            message_id?: string;
            run_id?: string;
            agent_id?: string;
            status?: components["schemas"]["RunStatus"];
            verification_status?: components["schemas"]["VerificationStatus"];
            citations?: components["schemas"]["RAGCitation"][];
            invalid_citation_ids?: string[];
            web_citations?: components["schemas"]["WebCitation"][];
            invalid_web_citation_ids?: string[];
        };
        ErrorChunk: {
            /** @constant */
            type: "error";
            error: string;
            code?: string;
            source?: string;
            category?: string;
            retryable?: boolean;
            /** Format: int64 */
            retry_after_ms?: number;
            request_id?: string;
        };
        ChatStreamEvent: components["schemas"]["ConversationChunk"] | components["schemas"]["RunStateChunk"] | components["schemas"]["RunProgressChunk"] | components["schemas"]["ModelDeltaChunk"] | components["schemas"]["ModelReasoningChunk"] | components["schemas"]["StageStateChunk"] | components["schemas"]["DoneChunk"] | components["schemas"]["ErrorChunk"] | components["schemas"]["RunEvent"];
    };
    responses: {
        /** @description Invalid request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Requested resource was not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Request conflicts with current resource state. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Run admission queue is full or temporarily unavailable. */
        TooManyRequests: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Internal server error. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        ConversationId: string;
        AgentId: string;
        RunId: string;
        ToolName: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listWorkspaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Owned Workspaces. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"][];
                };
            };
        };
    };
    createWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceCreateRequest"];
            };
        };
        responses: {
            /** @description Created Workspace. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Owned and granted Workspace. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteWorkspace: {
        parameters: {
            query?: {
                replacement_workspace_id?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Soft-deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            /** @description Workspace cannot currently be deleted. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceUpdateRequest"];
            };
        };
        responses: {
            /** @description Updated Workspace, preserving its ID. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Last active space, invalid replacement default, unfinished Run or uncertain effect prevents the change. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getIdentitySession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current authentication mode, identity and Workspace memberships. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentitySession"];
                };
            };
            /** @description Identity persistence unavailable; no local-mode fallback. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    startLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OIDC authorization redirect with state, nonce, S256 PKCE and prompt=login to require fresh authentication. */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    startRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to the IdP registration screen. */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            /** @description Cannot persist the authorization attempt. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    completeLogin: {
        parameters: {
            query?: {
                code?: string;
                state?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verified OIDC login ensures an idempotent personal Workspace before creating a host-only HttpOnly session and redirecting to the workbench. Revoked Memberships are not restored. */
            303: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            /** @description Invalid identity token or nonce. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Identity persistence or personal Workspace provisioning failed; no session is issued. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    signOut: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Local session revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Mutation Origin rejected. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API process health. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listConversations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversations visible in the current workspace. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    createConversation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConversationRequest"];
            };
        };
        responses: {
            /** @description Created conversation. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversation deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteConversationResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updateConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateConversationRequest"];
            };
        };
        responses: {
            /** @description Updated conversation. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listMessages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversation messages. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"][];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    streamChat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Server-sent stream of ChatStreamEvent values. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    listSkills: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operator-trusted Skill metadata, without directory paths or contents. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillMetadata"][];
                };
            };
        };
    };
    listAgents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active agents. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    createAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentConfigRequest"];
            };
        };
        responses: {
            /** @description Created agent. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent configuration. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    archiveAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent archived. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    updateAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentConfigRequest"];
            };
        };
        responses: {
            /** @description Updated agent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listRuns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runs ordered by the store. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listRunAttention: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Highest-priority operator attention item for each actionable Run. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperatorAttentionItem"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    continueRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContinueRunRequest"];
            };
        };
        responses: {
            /** @description Server-sent stream of ChatStreamEvent values. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    resumeRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeRunRequest"];
            };
        };
        responses: {
            /** @description Server-sent stream of ChatStreamEvent values. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    cancelRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Canceled or canceling run. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    verifyRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verification decision and resulting Run state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyRunResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    getRunReplay: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Replayable Run state and evidence. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunReplay"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    observeRunEvents: {
        parameters: {
            query?: {
                /** @description Resume after this durable Run event sequence. */
                after?: number;
            };
            header?: {
                /** @description SSE resume cursor; takes precedence over the after query parameter. */
                "Last-Event-ID"?: number;
            };
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Snapshot, durable event replay, and live Run events as server-sent events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    getRunUsage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run budget and append-only usage ledger. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunUsageLedger"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listCollaborationSteps: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Multi-Agent or Autonomous stages for the Run. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollaborationStep"][];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listTools: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tool catalog and current enabled state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolInfo"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    enableTool: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["ToolName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated tool catalog. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolInfo"][];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    disableTool: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["ToolName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated tool catalog. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolInfo"][];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
}
