/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["streamChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAgents"];
        put?: never;
        post: operations["createAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        get: operations["getAgent"];
        put?: never;
        post?: never;
        delete: operations["archiveAgent"];
        options?: never;
        head?: never;
        patch: operations["updateAgent"];
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/continue": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["continueRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resumeRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get: operations["getRunReplay"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get: operations["getRunUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/collaboration_steps": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get: operations["listCollaborationSteps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTools"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tools/{name}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["ToolName"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["enableTool"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tools/{name}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["ToolName"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["disableTool"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: string;
        };
        /** @enum {string} */
        ChatMode: "single" | "multi_agent" | "autonomous";
        /** @enum {string} */
        ChatExecutor: "native" | "langchaingo";
        /** @enum {string} */
        RunStatus: "queued" | "running" | "waiting_for_user" | "completed" | "failed" | "failed_recoverable" | "canceling" | "canceled";
        /** @enum {string} */
        VerificationStatus: "not_required" | "pending" | "running" | "passed" | "failed" | "blocked" | "stale";
        /** @enum {string} */
        VerifierType: "command" | "http" | "json_schema" | "text_constraints" | "citation";
        VerifierSpecInput: {
            id: string;
            type: components["schemas"]["VerifierType"];
            version?: string;
            required: boolean;
            /** Format: int64 */
            timeout_ms?: number;
            config: {
                [key: string]: unknown;
            };
        };
        VerificationPolicyInput: {
            /** @enum {string} */
            mode: "all_must_pass" | "any_may_pass";
            max_attempts: number;
            /** @enum {string} */
            on_exhausted: "fail" | "waiting_for_user";
        };
        CompletionContractInput: {
            /** @enum {string} */
            subject_type: "run_output";
            verifiers: components["schemas"]["VerifierSpecInput"][];
            policy: components["schemas"]["VerificationPolicyInput"];
        };
        CompletionContract: components["schemas"]["CompletionContractInput"] & {
            id: string;
            version: number;
            hash: string;
        };
        ChatRequest: {
            conversation_id?: string;
            agent_id?: string;
            message: string;
            mode?: components["schemas"]["ChatMode"];
            executor?: components["schemas"]["ChatExecutor"];
            completion_contract?: components["schemas"]["CompletionContractInput"];
        };
        ContinueRunRequest: {
            plan: string;
        };
        ResumeRunRequest: {
            user_input: string;
        };
        Conversation: {
            id: string;
            title: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Message: {
            id: string;
            conversation_id: string;
            /** @enum {string} */
            role: "user" | "assistant" | "system";
            content: string;
            /** Format: date-time */
            created_at: string;
        };
        AgentConfigRequest: {
            id?: string;
            name?: string;
            description?: string;
            system_prompt?: string;
            tools?: string[];
            memory_enabled?: boolean;
            retrieval_enabled?: boolean;
            executor?: components["schemas"]["ChatExecutor"];
        };
        Agent: {
            id: string;
            name: string;
            description: string;
            system_prompt: string;
            tools: string[];
            memory_enabled: boolean;
            retrieval_enabled: boolean;
            executor: components["schemas"]["ChatExecutor"];
            archived?: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ToolInfo: {
            name: string;
            description: string;
            parameters: {
                [key: string]: unknown;
            };
            enabled: boolean;
        };
        Run: {
            id: string;
            agent_id: string;
            conversation_id: string;
            status: components["schemas"]["RunStatus"];
            verification_status: components["schemas"]["VerificationStatus"];
            completion_contract?: components["schemas"]["CompletionContract"];
            error?: string;
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            execution_started_at?: string;
            /** Format: int64 */
            active_runtime_ms: number;
            /** Format: date-time */
            heartbeat_at?: string;
            /** Format: date-time */
            completed_at?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CollaborationStep: {
            id: string;
            run_id: string;
            conversation_id: string;
            role: string;
            agent_id?: string;
            /** @enum {string} */
            status: "queued" | "running" | "completed" | "failed";
            iteration?: number;
            input: string;
            output: string;
            error?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        RunEvent: {
            id: string;
            type: string;
            schema_version: number;
            /** Format: int64 */
            sequence: number;
            conversation_id?: string;
            run_id: string;
            stage_id?: string;
            turn_id?: string;
            parent_event_id?: string;
            payload: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            timestamp: string;
        };
        RunTraceSummary: {
            run_id: string;
            status: components["schemas"]["RunStatus"];
            /** Format: int64 */
            total_duration_ms: number;
            total_tokens: number;
            prompt_tokens: number;
            completion_tokens: number;
            token_usage_estimated: boolean;
            llm_calls: number;
            tool_calls: number;
            error_count: number;
        };
        RuntimeRunBudget: {
            max_model_calls?: number;
            max_prompt_tokens?: number;
            max_completion_tokens?: number;
            max_total_tokens?: number;
            max_tool_calls?: number;
            /** Format: int64 */
            max_runtime_ms?: number;
            /** Format: int64 */
            max_estimated_cost_micros?: number;
            /** Format: int64 */
            input_cost_per_million_tokens_micros?: number;
            /** Format: int64 */
            output_cost_per_million_tokens_micros?: number;
        };
        RunUsageTotals: {
            model_calls: number;
            tool_calls: number;
            prompt_tokens: number;
            completion_tokens: number;
            total_tokens: number;
            /** Format: int64 */
            estimated_cost_micros: number;
            open_reservations: number;
        };
        RunUsageEntry: {
            id: string;
            run_id: string;
            operation_id: string;
            stage_id?: string;
            turn_id?: string;
            /** @enum {string} */
            kind: "model.reservation" | "model.settlement" | "tool.execution";
            /** @enum {string} */
            purpose: "primary" | "router" | "compaction";
            model?: string;
            tool_name?: string;
            model_calls?: number;
            tool_calls?: number;
            prompt_tokens?: number;
            completion_tokens?: number;
            total_tokens?: number;
            /** Format: int64 */
            estimated_cost_micros?: number;
            estimated?: boolean;
            /** Format: date-time */
            timestamp: string;
        };
        RunUsageLedger: {
            run_id: string;
            budget: components["schemas"]["RuntimeRunBudget"];
            totals: components["schemas"]["RunUsageTotals"];
            entries: components["schemas"]["RunUsageEntry"][];
            /** Format: date-time */
            updated_at?: string;
        };
        VerificationEvidence: {
            id: string;
            run_id: string;
            verifier_id: string;
            status: components["schemas"]["VerificationStatus"];
        } & {
            [key: string]: unknown;
        };
        VerificationArtifact: {
            id: string;
            run_id: string;
            evidence_id: string;
            kind: string;
        } & {
            [key: string]: unknown;
        };
        RunReplay: {
            run: components["schemas"]["Run"];
            runtime_snapshot?: {
                [key: string]: unknown;
            };
            conversation: components["schemas"]["Conversation"];
            messages: components["schemas"]["Message"][];
            steps: components["schemas"]["CollaborationStep"][];
            summary: components["schemas"]["RunTraceSummary"];
            usage_ledger: components["schemas"]["RunUsageLedger"];
            run_events: components["schemas"]["RunEvent"][];
            verification_evidence: components["schemas"]["VerificationEvidence"][];
            verification_artifacts: components["schemas"]["VerificationArtifact"][];
        };
        VerificationDecision: {
            status: components["schemas"]["VerificationStatus"];
            allow_completion: boolean;
            attempt: number;
            subject_hash: string;
            run_status: components["schemas"]["RunStatus"];
            summary: string;
        };
        VerifyRunResponse: {
            run: components["schemas"]["Run"];
            decision: components["schemas"]["VerificationDecision"];
        };
        ConversationChunk: {
            /** @constant */
            type: "conversation";
            conversation_id: string;
        };
        RunStateChunk: {
            /** @constant */
            type: "run_state";
            conversation_id: string;
            run_id: string;
            agent_id: string;
            status: components["schemas"]["RunStatus"];
        };
        RunProgressChunk: {
            /** @constant */
            type: "run_progress";
            conversation_id: string;
            run_id: string;
            agent_id?: string;
            iteration?: number;
            max_iterations?: number;
            elapsed_seconds?: number;
            max_runtime_seconds?: number;
            output_chars?: number;
            max_output_chars?: number;
            tool_calls?: number;
            max_tool_calls?: number;
            stop_reason?: string;
        };
        ModelDeltaChunk: {
            /** @constant */
            type: "model_delta";
            delta: string;
        };
        StageStateChunk: {
            /** @constant */
            type: "stage_state";
            conversation_id: string;
            run_id: string;
            agent_id?: string;
            role: string;
            status: string;
            iteration?: number;
            input?: string;
            output?: string;
            error?: string;
        };
        DoneChunk: {
            /** @constant */
            type: "done";
            conversation_id: string;
            title?: string;
            message_id?: string;
            run_id?: string;
            agent_id?: string;
            status?: components["schemas"]["RunStatus"];
            verification_status?: components["schemas"]["VerificationStatus"];
        };
        ErrorChunk: {
            /** @constant */
            type: "error";
            error: string;
        };
        ChatStreamEvent: components["schemas"]["ConversationChunk"] | components["schemas"]["RunStateChunk"] | components["schemas"]["RunProgressChunk"] | components["schemas"]["ModelDeltaChunk"] | components["schemas"]["StageStateChunk"] | components["schemas"]["DoneChunk"] | components["schemas"]["ErrorChunk"] | components["schemas"]["RunEvent"];
    };
    responses: {
        /** @description Invalid request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Requested resource was not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Request conflicts with current resource state. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Run admission queue is full or temporarily unavailable. */
        TooManyRequests: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Internal server error. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        AgentId: string;
        RunId: string;
        ToolName: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    streamChat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Server-sent stream of ChatStreamEvent values. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    listAgents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active agents. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    createAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentConfigRequest"];
            };
        };
        responses: {
            /** @description Created agent. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent configuration. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    archiveAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent archived. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    updateAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentConfigRequest"];
            };
        };
        responses: {
            /** @description Updated agent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listRuns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runs ordered by the store. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    continueRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContinueRunRequest"];
            };
        };
        responses: {
            /** @description Server-sent stream of ChatStreamEvent values. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    resumeRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeRunRequest"];
            };
        };
        responses: {
            /** @description Server-sent stream of ChatStreamEvent values. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    cancelRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Canceled or canceling run. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    verifyRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verification decision and resulting Run state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyRunResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    getRunReplay: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Replayable Run state and evidence. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunReplay"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getRunUsage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run budget and append-only usage ledger. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunUsageLedger"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listCollaborationSteps: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Multi-Agent or Autonomous stages for the Run. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollaborationStep"][];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listTools: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tool catalog and current enabled state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolInfo"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    enableTool: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["ToolName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated tool catalog. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolInfo"][];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    disableTool: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["ToolName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated tool catalog. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolInfo"][];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
}
