// Package apicontract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apicontract

import (
	"encoding/json"
	"fmt"
	"time"
)

// Defines values for ChatMode.
const (
	Autonomous ChatMode = "autonomous"
	MultiAgent ChatMode = "multi_agent"
	Single     ChatMode = "single"
)

// Valid indicates whether the value is a known member of the ChatMode enum.
func (e ChatMode) Valid() bool {
	switch e {
	case Autonomous:
		return true
	case MultiAgent:
		return true
	case Single:
		return true
	default:
		return false
	}
}

// Defines values for CompletionContractSubjectType.
const (
	CompletionContractSubjectTypeRunOutput CompletionContractSubjectType = "run_output"
)

// Valid indicates whether the value is a known member of the CompletionContractSubjectType enum.
func (e CompletionContractSubjectType) Valid() bool {
	switch e {
	case CompletionContractSubjectTypeRunOutput:
		return true
	default:
		return false
	}
}

// Defines values for CompletionContractInputSubjectType.
const (
	CompletionContractInputSubjectTypeRunOutput CompletionContractInputSubjectType = "run_output"
)

// Valid indicates whether the value is a known member of the CompletionContractInputSubjectType enum.
func (e CompletionContractInputSubjectType) Valid() bool {
	switch e {
	case CompletionContractInputSubjectTypeRunOutput:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for IdentitySessionMode.
const (
	Local IdentitySessionMode = "local"
	Oidc  IdentitySessionMode = "oidc"
)

// Valid indicates whether the value is a known member of the IdentitySessionMode enum.
func (e IdentitySessionMode) Valid() bool {
	switch e {
	case Local:
		return true
	case Oidc:
		return true
	default:
		return false
	}
}

// Defines values for MessageRole.
const (
	Assistant MessageRole = "assistant"
	System    MessageRole = "system"
	User      MessageRole = "user"
)

// Valid indicates whether the value is a known member of the MessageRole enum.
func (e MessageRole) Valid() bool {
	switch e {
	case Assistant:
		return true
	case System:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for MessageReasoningFormat.
const (
	DeepseekReasoningContent MessageReasoningFormat = "deepseek_reasoning_content"
)

// Valid indicates whether the value is a known member of the MessageReasoningFormat enum.
func (e MessageReasoningFormat) Valid() bool {
	switch e {
	case DeepseekReasoningContent:
		return true
	default:
		return false
	}
}

// Defines values for MessageReasoningStatus.
const (
	Complete MessageReasoningStatus = "complete"
)

// Valid indicates whether the value is a known member of the MessageReasoningStatus enum.
func (e MessageReasoningStatus) Valid() bool {
	switch e {
	case Complete:
		return true
	default:
		return false
	}
}

// Defines values for ModelRequestCaptureMode.
const (
	Full         ModelRequestCaptureMode = "full"
	MetadataOnly ModelRequestCaptureMode = "metadata_only"
	Redacted     ModelRequestCaptureMode = "redacted"
)

// Valid indicates whether the value is a known member of the ModelRequestCaptureMode enum.
func (e ModelRequestCaptureMode) Valid() bool {
	switch e {
	case Full:
		return true
	case MetadataOnly:
		return true
	case Redacted:
		return true
	default:
		return false
	}
}

// Defines values for ModelRequestDebugResponseReconstructabilityStatus.
const (
	Invalid ModelRequestDebugResponseReconstructabilityStatus = "invalid"
	Valid   ModelRequestDebugResponseReconstructabilityStatus = "valid"
)

// Valid indicates whether the value is a known member of the ModelRequestDebugResponseReconstructabilityStatus enum.
func (e ModelRequestDebugResponseReconstructabilityStatus) Valid() bool {
	switch e {
	case Invalid:
		return true
	case Valid:
		return true
	default:
		return false
	}
}

// Defines values for OperatorAttentionItemReason.
const (
	OperatorAttentionItemReasonBudgetExhausted        OperatorAttentionItemReason = "budget_exhausted"
	OperatorAttentionItemReasonFailure                OperatorAttentionItemReason = "failure"
	OperatorAttentionItemReasonReconciliationRequired OperatorAttentionItemReason = "reconciliation_required"
	OperatorAttentionItemReasonRecoveryAvailable      OperatorAttentionItemReason = "recovery_available"
	OperatorAttentionItemReasonVerificationAttention  OperatorAttentionItemReason = "verification_attention"
	OperatorAttentionItemReasonWaitingForUser         OperatorAttentionItemReason = "waiting_for_user"
)

// Valid indicates whether the value is a known member of the OperatorAttentionItemReason enum.
func (e OperatorAttentionItemReason) Valid() bool {
	switch e {
	case OperatorAttentionItemReasonBudgetExhausted:
		return true
	case OperatorAttentionItemReasonFailure:
		return true
	case OperatorAttentionItemReasonReconciliationRequired:
		return true
	case OperatorAttentionItemReasonRecoveryAvailable:
		return true
	case OperatorAttentionItemReasonVerificationAttention:
		return true
	case OperatorAttentionItemReasonWaitingForUser:
		return true
	default:
		return false
	}
}

// Defines values for PartialOutputChannel.
const (
	Answer    PartialOutputChannel = "answer"
	Reasoning PartialOutputChannel = "reasoning"
)

// Valid indicates whether the value is a known member of the PartialOutputChannel enum.
func (e PartialOutputChannel) Valid() bool {
	switch e {
	case Answer:
		return true
	case Reasoning:
		return true
	default:
		return false
	}
}

// Defines values for PartialOutputStatus.
const (
	PartialOutputStatusFinal       PartialOutputStatus = "final"
	PartialOutputStatusInterrupted PartialOutputStatus = "interrupted"
	PartialOutputStatusProvisional PartialOutputStatus = "provisional"
	PartialOutputStatusRetracted   PartialOutputStatus = "retracted"
)

// Valid indicates whether the value is a known member of the PartialOutputStatus enum.
func (e PartialOutputStatus) Valid() bool {
	switch e {
	case PartialOutputStatusFinal:
		return true
	case PartialOutputStatusInterrupted:
		return true
	case PartialOutputStatusProvisional:
		return true
	case PartialOutputStatusRetracted:
		return true
	default:
		return false
	}
}

// Defines values for RunInputKind.
const (
	RunInputKindFollowUp RunInputKind = "follow_up"
	RunInputKindSteer    RunInputKind = "steer"
)

// Valid indicates whether the value is a known member of the RunInputKind enum.
func (e RunInputKind) Valid() bool {
	switch e {
	case RunInputKindFollowUp:
		return true
	case RunInputKindSteer:
		return true
	default:
		return false
	}
}

// Defines values for RunInputStatus.
const (
	RunInputStatusApplied   RunInputStatus = "applied"
	RunInputStatusExpired   RunInputStatus = "expired"
	RunInputStatusQueued    RunInputStatus = "queued"
	RunInputStatusWithdrawn RunInputStatus = "withdrawn"
)

// Valid indicates whether the value is a known member of the RunInputStatus enum.
func (e RunInputStatus) Valid() bool {
	switch e {
	case RunInputStatusApplied:
		return true
	case RunInputStatusExpired:
		return true
	case RunInputStatusQueued:
		return true
	case RunInputStatusWithdrawn:
		return true
	default:
		return false
	}
}

// Defines values for RunInputRequestKind.
const (
	RunInputRequestKindFollowUp RunInputRequestKind = "follow_up"
	RunInputRequestKindSteer    RunInputRequestKind = "steer"
)

// Valid indicates whether the value is a known member of the RunInputRequestKind enum.
func (e RunInputRequestKind) Valid() bool {
	switch e {
	case RunInputRequestKindFollowUp:
		return true
	case RunInputRequestKindSteer:
		return true
	default:
		return false
	}
}

// Defines values for RunStatus.
const (
	RunStatusCanceled          RunStatus = "canceled"
	RunStatusCanceling         RunStatus = "canceling"
	RunStatusCompleted         RunStatus = "completed"
	RunStatusFailed            RunStatus = "failed"
	RunStatusFailedRecoverable RunStatus = "failed_recoverable"
	RunStatusQueued            RunStatus = "queued"
	RunStatusRunning           RunStatus = "running"
	RunStatusWaitingForUser    RunStatus = "waiting_for_user"
)

// Valid indicates whether the value is a known member of the RunStatus enum.
func (e RunStatus) Valid() bool {
	switch e {
	case RunStatusCanceled:
		return true
	case RunStatusCanceling:
		return true
	case RunStatusCompleted:
		return true
	case RunStatusFailed:
		return true
	case RunStatusFailedRecoverable:
		return true
	case RunStatusQueued:
		return true
	case RunStatusRunning:
		return true
	case RunStatusWaitingForUser:
		return true
	default:
		return false
	}
}

// Defines values for RunUsageEntryKind.
const (
	ModelReservation RunUsageEntryKind = "model.reservation"
	ModelSettlement  RunUsageEntryKind = "model.settlement"
	ToolExecution    RunUsageEntryKind = "tool.execution"
)

// Valid indicates whether the value is a known member of the RunUsageEntryKind enum.
func (e RunUsageEntryKind) Valid() bool {
	switch e {
	case ModelReservation:
		return true
	case ModelSettlement:
		return true
	case ToolExecution:
		return true
	default:
		return false
	}
}

// Defines values for RunUsageEntryPurpose.
const (
	Compaction RunUsageEntryPurpose = "compaction"
	Primary    RunUsageEntryPurpose = "primary"
	Router     RunUsageEntryPurpose = "router"
)

// Valid indicates whether the value is a known member of the RunUsageEntryPurpose enum.
func (e RunUsageEntryPurpose) Valid() bool {
	switch e {
	case Compaction:
		return true
	case Primary:
		return true
	case Router:
		return true
	default:
		return false
	}
}

// Defines values for SkillEvidenceActivation.
const (
	SkillEvidenceActivationExplicit    SkillEvidenceActivation = "explicit"
	SkillEvidenceActivationModel       SkillEvidenceActivation = "model"
	SkillEvidenceActivationNotObserved SkillEvidenceActivation = "not_observed"
)

// Valid indicates whether the value is a known member of the SkillEvidenceActivation enum.
func (e SkillEvidenceActivation) Valid() bool {
	switch e {
	case SkillEvidenceActivationExplicit:
		return true
	case SkillEvidenceActivationModel:
		return true
	case SkillEvidenceActivationNotObserved:
		return true
	default:
		return false
	}
}

// Defines values for SkillEvidenceInstructions.
const (
	SkillEvidenceInstructionsIncluded    SkillEvidenceInstructions = "included"
	SkillEvidenceInstructionsNotObserved SkillEvidenceInstructions = "not_observed"
)

// Valid indicates whether the value is a known member of the SkillEvidenceInstructions enum.
func (e SkillEvidenceInstructions) Valid() bool {
	switch e {
	case SkillEvidenceInstructionsIncluded:
		return true
	case SkillEvidenceInstructionsNotObserved:
		return true
	default:
		return false
	}
}

// Defines values for TaskBlockerStatus.
const (
	Open     TaskBlockerStatus = "open"
	Resolved TaskBlockerStatus = "resolved"
)

// Valid indicates whether the value is a known member of the TaskBlockerStatus enum.
func (e TaskBlockerStatus) Valid() bool {
	switch e {
	case Open:
		return true
	case Resolved:
		return true
	default:
		return false
	}
}

// Defines values for TaskItemStatus.
const (
	TaskItemStatusCanceled   TaskItemStatus = "canceled"
	TaskItemStatusCompleted  TaskItemStatus = "completed"
	TaskItemStatusInProgress TaskItemStatus = "in_progress"
	TaskItemStatusPending    TaskItemStatus = "pending"
)

// Valid indicates whether the value is a known member of the TaskItemStatus enum.
func (e TaskItemStatus) Valid() bool {
	switch e {
	case TaskItemStatusCanceled:
		return true
	case TaskItemStatusCompleted:
		return true
	case TaskItemStatusInProgress:
		return true
	case TaskItemStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for TaskStateOperationType.
const (
	AddArtifactRef    TaskStateOperationType = "add_artifact_ref"
	AddDecision       TaskStateOperationType = "add_decision"
	ClearGoal         TaskStateOperationType = "clear_goal"
	RemoveArtifactRef TaskStateOperationType = "remove_artifact_ref"
	RemoveBlocker     TaskStateOperationType = "remove_blocker"
	RemoveConstraint  TaskStateOperationType = "remove_constraint"
	RemoveTask        TaskStateOperationType = "remove_task"
	ResolveBlocker    TaskStateOperationType = "resolve_blocker"
	SetGoal           TaskStateOperationType = "set_goal"
	SetTaskStatus     TaskStateOperationType = "set_task_status"
	UpsertBlocker     TaskStateOperationType = "upsert_blocker"
	UpsertConstraint  TaskStateOperationType = "upsert_constraint"
	UpsertTask        TaskStateOperationType = "upsert_task"
)

// Valid indicates whether the value is a known member of the TaskStateOperationType enum.
func (e TaskStateOperationType) Valid() bool {
	switch e {
	case AddArtifactRef:
		return true
	case AddDecision:
		return true
	case ClearGoal:
		return true
	case RemoveArtifactRef:
		return true
	case RemoveBlocker:
		return true
	case RemoveConstraint:
		return true
	case RemoveTask:
		return true
	case ResolveBlocker:
		return true
	case SetGoal:
		return true
	case SetTaskStatus:
		return true
	case UpsertBlocker:
		return true
	case UpsertConstraint:
		return true
	case UpsertTask:
		return true
	default:
		return false
	}
}

// Defines values for ToolEffectReconciliationAction.
const (
	Compensate       ToolEffectReconciliationAction = "compensate"
	ConfirmCommitted ToolEffectReconciliationAction = "confirm_committed"
	ConfirmFailed    ToolEffectReconciliationAction = "confirm_failed"
	RetryWithSameKey ToolEffectReconciliationAction = "retry_with_same_key"
)

// Valid indicates whether the value is a known member of the ToolEffectReconciliationAction enum.
func (e ToolEffectReconciliationAction) Valid() bool {
	switch e {
	case Compensate:
		return true
	case ConfirmCommitted:
		return true
	case ConfirmFailed:
		return true
	case RetryWithSameKey:
		return true
	default:
		return false
	}
}

// Defines values for ToolProgressStatus.
const (
	ToolProgressStatusCompleted   ToolProgressStatus = "completed"
	ToolProgressStatusFailed      ToolProgressStatus = "failed"
	ToolProgressStatusInterrupted ToolProgressStatus = "interrupted"
	ToolProgressStatusRunning     ToolProgressStatus = "running"
)

// Valid indicates whether the value is a known member of the ToolProgressStatus enum.
func (e ToolProgressStatus) Valid() bool {
	switch e {
	case ToolProgressStatusCompleted:
		return true
	case ToolProgressStatusFailed:
		return true
	case ToolProgressStatusInterrupted:
		return true
	case ToolProgressStatusRunning:
		return true
	default:
		return false
	}
}

// Defines values for UsageBreakdownSource.
const (
	DeepseekCache  UsageBreakdownSource = "deepseek_cache"
	InvalidDetails UsageBreakdownSource = "invalid_details"
	OpenaiDetails  UsageBreakdownSource = "openai_details"
)

// Valid indicates whether the value is a known member of the UsageBreakdownSource enum.
func (e UsageBreakdownSource) Valid() bool {
	switch e {
	case DeepseekCache:
		return true
	case InvalidDetails:
		return true
	case OpenaiDetails:
		return true
	default:
		return false
	}
}

// Defines values for UsageCostDetailsStatus.
const (
	Estimated UsageCostDetailsStatus = "estimated"
	Unknown   UsageCostDetailsStatus = "unknown"
)

// Valid indicates whether the value is a known member of the UsageCostDetailsStatus enum.
func (e UsageCostDetailsStatus) Valid() bool {
	switch e {
	case Estimated:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for VerificationPolicyInputMode.
const (
	AllMustPass VerificationPolicyInputMode = "all_must_pass"
	AnyMayPass  VerificationPolicyInputMode = "any_may_pass"
)

// Valid indicates whether the value is a known member of the VerificationPolicyInputMode enum.
func (e VerificationPolicyInputMode) Valid() bool {
	switch e {
	case AllMustPass:
		return true
	case AnyMayPass:
		return true
	default:
		return false
	}
}

// Defines values for VerificationPolicyInputOnExhausted.
const (
	VerificationPolicyInputOnExhaustedFail           VerificationPolicyInputOnExhausted = "fail"
	VerificationPolicyInputOnExhaustedWaitingForUser VerificationPolicyInputOnExhausted = "waiting_for_user"
)

// Valid indicates whether the value is a known member of the VerificationPolicyInputOnExhausted enum.
func (e VerificationPolicyInputOnExhausted) Valid() bool {
	switch e {
	case VerificationPolicyInputOnExhaustedFail:
		return true
	case VerificationPolicyInputOnExhaustedWaitingForUser:
		return true
	default:
		return false
	}
}

// Defines values for VerificationStatus.
const (
	VerificationStatusBlocked     VerificationStatus = "blocked"
	VerificationStatusFailed      VerificationStatus = "failed"
	VerificationStatusNotRequired VerificationStatus = "not_required"
	VerificationStatusPassed      VerificationStatus = "passed"
	VerificationStatusPending     VerificationStatus = "pending"
	VerificationStatusRunning     VerificationStatus = "running"
	VerificationStatusStale       VerificationStatus = "stale"
)

// Valid indicates whether the value is a known member of the VerificationStatus enum.
func (e VerificationStatus) Valid() bool {
	switch e {
	case VerificationStatusBlocked:
		return true
	case VerificationStatusFailed:
		return true
	case VerificationStatusNotRequired:
		return true
	case VerificationStatusPassed:
		return true
	case VerificationStatusPending:
		return true
	case VerificationStatusRunning:
		return true
	case VerificationStatusStale:
		return true
	default:
		return false
	}
}

// Defines values for VerifierType.
const (
	AnswerRelevance VerifierType = "answer_relevance"
	Citation        VerifierType = "citation"
	Command         VerifierType = "command"
	GroundedAnswer  VerifierType = "grounded_answer"
	Http            VerifierType = "http"
	JsonSchema      VerifierType = "json_schema"
	TextConstraints VerifierType = "text_constraints"
)

// Valid indicates whether the value is a known member of the VerifierType enum.
func (e VerifierType) Valid() bool {
	switch e {
	case AnswerRelevance:
		return true
	case Citation:
		return true
	case Command:
		return true
	case GroundedAnswer:
		return true
	case Http:
		return true
	case JsonSchema:
		return true
	case TextConstraints:
		return true
	default:
		return false
	}
}

// Defines values for WorkspaceStatus.
const (
	WorkspaceStatusActive   WorkspaceStatus = "active"
	WorkspaceStatusArchived WorkspaceStatus = "archived"
)

// Valid indicates whether the value is a known member of the WorkspaceStatus enum.
func (e WorkspaceStatus) Valid() bool {
	switch e {
	case WorkspaceStatusActive:
		return true
	case WorkspaceStatusArchived:
		return true
	default:
		return false
	}
}

// Defines values for WorkspaceUpdateRequestStatus.
const (
	WorkspaceUpdateRequestStatusActive   WorkspaceUpdateRequestStatus = "active"
	WorkspaceUpdateRequestStatusArchived WorkspaceUpdateRequestStatus = "archived"
)

// Valid indicates whether the value is a known member of the WorkspaceUpdateRequestStatus enum.
func (e WorkspaceUpdateRequestStatus) Valid() bool {
	switch e {
	case WorkspaceUpdateRequestStatusActive:
		return true
	case WorkspaceUpdateRequestStatusArchived:
		return true
	default:
		return false
	}
}

// Agent defines model for Agent.
type Agent struct {
	Archived    *bool     `json:"archived,omitempty"`
	CreatedAt   time.Time `json:"created_at"`
	Description string    `json:"description"`
	Executor    *string   `json:"executor,omitempty"`
	Id          string    `json:"id"`

	// IsTemplate Shared read-only profile; POST a copy to configure it in a Workspace.
	IsTemplate       *bool              `json:"is_template,omitempty"`
	MemoryEnabled    bool               `json:"memory_enabled"`
	Name             string             `json:"name"`
	RetrievalEnabled bool               `json:"retrieval_enabled"`
	RoutingHints     *AgentRoutingHints `json:"routing_hints,omitempty"`
	Skills           *[]string          `json:"skills,omitempty"`
	SystemPrompt     string             `json:"system_prompt"`
	Tools            []string           `json:"tools"`
	UpdatedAt        time.Time          `json:"updated_at"`

	// WorkspaceId Owning Workspace; absent for shared read-only templates.
	WorkspaceId *string `json:"workspace_id,omitempty"`
}

// AgentConfigRequest defines model for AgentConfigRequest.
type AgentConfigRequest struct {
	Description      *string            `json:"description,omitempty"`
	Id               *string            `json:"id,omitempty"`
	MemoryEnabled    *bool              `json:"memory_enabled,omitempty"`
	Name             *string            `json:"name,omitempty"`
	RetrievalEnabled *bool              `json:"retrieval_enabled,omitempty"`
	RoutingHints     *AgentRoutingHints `json:"routing_hints,omitempty"`
	Skills           *[]string          `json:"skills,omitempty"`
	SystemPrompt     *string            `json:"system_prompt,omitempty"`
	Tools            *[]string          `json:"tools,omitempty"`
}

// AgentRoutingHints defines model for AgentRoutingHints.
type AgentRoutingHints struct {
	Capabilities []string `json:"capabilities"`
	Exclusions   []string `json:"exclusions"`
	TaskExamples []string `json:"task_examples"`
}

// AgentRoutingRequirements defines model for AgentRoutingRequirements.
type AgentRoutingRequirements struct {
	PreferredCapabilities *[]string `json:"preferred_capabilities,omitempty"`
	ProhibitedTools       *[]string `json:"prohibited_tools,omitempty"`
	RequireMemory         *bool     `json:"require_memory,omitempty"`
	RequireRetrieval      *bool     `json:"require_retrieval,omitempty"`
	RequiredTools         *[]string `json:"required_tools,omitempty"`
}

// ChatMode defines model for ChatMode.
type ChatMode string

// ChatRequest defines model for ChatRequest.
type ChatRequest struct {
	AgentId            *string                  `json:"agent_id,omitempty"`
	CompletionContract *CompletionContractInput `json:"completion_contract,omitempty"`
	ConversationId     *string                  `json:"conversation_id,omitempty"`
	Message            string                   `json:"message"`
	Mode               *ChatMode                `json:"mode,omitempty"`
	WorkspaceId        *string                  `json:"workspace_id,omitempty"`
}

// CollaborationStep defines model for CollaborationStep.
type CollaborationStep struct {
	AgentId        *string   `json:"agent_id,omitempty"`
	ConversationId string    `json:"conversation_id"`
	CreatedAt      time.Time `json:"created_at"`
	Error          *string   `json:"error,omitempty"`
	Id             string    `json:"id"`
	Input          string    `json:"input"`
	Iteration      *int      `json:"iteration,omitempty"`
	Output         string    `json:"output"`
	Role           string    `json:"role"`
	RunId          string    `json:"run_id"`
	Status         string    `json:"status"`
	UpdatedAt      time.Time `json:"updated_at"`
}

// CompletionContract defines model for CompletionContract.
type CompletionContract struct {
	Hash        string                        `json:"hash"`
	Id          string                        `json:"id"`
	Policy      VerificationPolicyInput       `json:"policy"`
	SubjectType CompletionContractSubjectType `json:"subject_type"`
	Verifiers   []VerifierSpecInput           `json:"verifiers"`
	Version     int                           `json:"version"`
}

// CompletionContractSubjectType defines model for CompletionContract.SubjectType.
type CompletionContractSubjectType string

// CompletionContractInput defines model for CompletionContractInput.
type CompletionContractInput struct {
	Policy      VerificationPolicyInput            `json:"policy"`
	SubjectType CompletionContractInputSubjectType `json:"subject_type"`
	Verifiers   []VerifierSpecInput                `json:"verifiers"`
}

// CompletionContractInputSubjectType defines model for CompletionContractInput.SubjectType.
type CompletionContractInputSubjectType string

// ContinueRunRequest defines model for ContinueRunRequest.
type ContinueRunRequest struct {
	Plan                string                    `json:"plan"`
	RoutingRequirements *AgentRoutingRequirements `json:"routing_requirements,omitempty"`
}

// Conversation defines model for Conversation.
type Conversation struct {
	CreatedAt   time.Time `json:"created_at"`
	Id          string    `json:"id"`
	Title       string    `json:"title"`
	UpdatedAt   time.Time `json:"updated_at"`
	WorkspaceId string    `json:"workspace_id"`
}

// CreateConversationRequest defines model for CreateConversationRequest.
type CreateConversationRequest struct {
	Title string `json:"title"`
}

// DeleteConversationResponse defines model for DeleteConversationResponse.
type DeleteConversationResponse struct {
	Deleted bool `json:"deleted"`
}

// EpisodeError defines model for EpisodeError.
type EpisodeError struct {
	Category  *string `json:"category,omitempty"`
	EventId   *string `json:"event_id,omitempty"`
	Kind      *string `json:"kind,omitempty"`
	Message   string  `json:"message"`
	Retryable *bool   `json:"retryable,omitempty"`
	Source    string  `json:"source"`
	StepId    *string `json:"step_id,omitempty"`
}

// EpisodeLLMCall defines model for EpisodeLLMCall.
type EpisodeLLMCall struct {
	AgentId             *string `json:"agent_id,omitempty"`
	CompletionTokens    *int    `json:"completion_tokens,omitempty"`
	DurationMs          *int64  `json:"duration_ms,omitempty"`
	EventId             string  `json:"event_id"`
	Framework           *string `json:"framework,omitempty"`
	Model               *string `json:"model,omitempty"`
	OutputChars         *int    `json:"output_chars,omitempty"`
	PromptTokens        *int    `json:"prompt_tokens,omitempty"`
	Role                *string `json:"role,omitempty"`
	StepId              *string `json:"step_id,omitempty"`
	TokenUsageEstimated *bool   `json:"token_usage_estimated,omitempty"`
	TotalTokens         *int    `json:"total_tokens,omitempty"`
}

// EpisodeReport defines model for EpisodeReport.
type EpisodeReport struct {
	Agent        Agent                `json:"agent"`
	Conversation Conversation         `json:"conversation"`
	Errors       *[]EpisodeError      `json:"errors"`
	FinalOutput  string               `json:"final_output"`
	LlmCalls     *[]EpisodeLLMCall    `json:"llm_calls"`
	Messages     *[]Message           `json:"messages"`
	Retrievals   EpisodeRetrievals    `json:"retrievals"`
	Run          Run                  `json:"run"`
	Steps        *[]CollaborationStep `json:"steps"`
	Task         string               `json:"task"`
	ToolCalls    *[]EpisodeToolCall   `json:"tool_calls"`
	TraceSummary RunTraceSummary      `json:"trace_summary"`
	Verification EpisodeVerification  `json:"verification"`
}

// EpisodeRetrievals defines model for EpisodeRetrievals.
type EpisodeRetrievals struct {
	Chunks     *[]map[string]interface{} `json:"chunks"`
	EventCount int                       `json:"event_count"`
	Memories   *[]map[string]interface{} `json:"memories"`
}

// EpisodeToolCall defines model for EpisodeToolCall.
type EpisodeToolCall struct {
	DurationMs *int64  `json:"duration_ms,omitempty"`
	Error      *string `json:"error,omitempty"`
	EventId    string  `json:"event_id"`
	StepId     *string `json:"step_id,omitempty"`
	ToolCallId *string `json:"tool_call_id,omitempty"`
	ToolName   *string `json:"tool_name,omitempty"`
}

// EpisodeVerification defines model for EpisodeVerification.
type EpisodeVerification struct {
	Artifacts   *[]VerificationArtifact `json:"artifacts"`
	Contract    *map[string]interface{} `json:"contract,omitempty"`
	Evidence    *[]string               `json:"evidence"`
	Records     *[]VerificationEvidence `json:"records"`
	Status      string                  `json:"status"`
	SubjectHash *string                 `json:"subject_hash,omitempty"`
	Warnings    *[]string               `json:"warnings"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Category  *string `json:"category,omitempty"`
	Code      *string `json:"code,omitempty"`
	Error     string  `json:"error"`
	Operation *string `json:"operation,omitempty"`
	RequestId *string `json:"request_id,omitempty"`
	Retryable *bool   `json:"retryable,omitempty"`
	Source    *string `json:"source,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// IdentitySession defines model for IdentitySession.
type IdentitySession struct {
	Authenticated bool                `json:"authenticated"`
	Mode          IdentitySessionMode `json:"mode"`

	// PersonalWorkspace Current owned active default Workspace ID; selection may change, absent when access is revoked. Retained field name for session contract compatibility.
	PersonalWorkspace *string       `json:"personal_workspace,omitempty"`
	User              *IdentityUser `json:"user"`
	Workspaces        []string      `json:"workspaces"`
}

// IdentitySessionMode defines model for IdentitySession.Mode.
type IdentitySessionMode string

// IdentityUser defines model for IdentityUser.
type IdentityUser struct {
	Id      string `json:"id"`
	Name    string `json:"name"`
	Subject string `json:"subject"`
}

// Message defines model for Message.
type Message struct {
	Citations      *[]RAGCitation `json:"citations,omitempty"`
	Content        string         `json:"content"`
	ConversationId string         `json:"conversation_id"`
	CreatedAt      time.Time      `json:"created_at"`
	Id             string         `json:"id"`

	// Reasoning Sanitized completed provider reasoning associated with this assistant answer; display-only, not model input.
	Reasoning    *[]MessageReasoning `json:"reasoning,omitempty"`
	Role         MessageRole         `json:"role"`
	WebCitations *[]WebCitation      `json:"web_citations,omitempty"`
	WorkspaceId  string              `json:"workspace_id"`
}

// MessageRole defines model for Message.Role.
type MessageRole string

// MessageReasoning defines model for MessageReasoning.
type MessageReasoning struct {
	Format      MessageReasoningFormat `json:"format"`
	ModelCallId string                 `json:"model_call_id"`
	RunId       string                 `json:"run_id"`
	StageId     *string                `json:"stage_id,omitempty"`
	Status      MessageReasoningStatus `json:"status"`

	// Text Redacted plain text
	Text      *string `json:"text,omitempty"`
	Truncated *bool   `json:"truncated,omitempty"`
	TurnId    string  `json:"turn_id"`
}

// MessageReasoningFormat defines model for MessageReasoning.Format.
type MessageReasoningFormat string

// MessageReasoningStatus defines model for MessageReasoning.Status.
type MessageReasoningStatus string

// ModelRequestCapture defines model for ModelRequestCapture.
type ModelRequestCapture struct {
	Content           *string                 `json:"content,omitempty"`
	ContentHash       *string                 `json:"content_hash,omitempty"`
	Expired           bool                    `json:"expired"`
	ExpiresAt         *time.Time              `json:"expires_at,omitempty"`
	Mode              ModelRequestCaptureMode `json:"mode"`
	OriginalBytes     int                     `json:"original_bytes"`
	Reconstructable   bool                    `json:"reconstructable"`
	Redacted          bool                    `json:"redacted"`
	RedactionCount    int                     `json:"redaction_count"`
	RedactionStrategy *string                 `json:"redaction_strategy,omitempty"`
	StoredBytes       int                     `json:"stored_bytes"`
	Truncated         bool                    `json:"truncated"`
}

// ModelRequestCaptureMode defines model for ModelRequestCapture.Mode.
type ModelRequestCaptureMode string

// ModelRequestDebugRecord defines model for ModelRequestDebugRecord.
type ModelRequestDebugRecord struct {
	Capture  ModelRequestCapture  `json:"capture"`
	Envelope ModelRequestEnvelope `json:"envelope"`

	// Manifest Context Manifest metadata
	Manifest   *map[string]interface{} `json:"manifest,omitempty"`
	SourceDiff ModelRequestSourceDiff  `json:"source_diff"`
}

// ModelRequestDebugResponse defines model for ModelRequestDebugResponse.
type ModelRequestDebugResponse struct {
	InvariantError           *string                                           `json:"invariant_error,omitempty"`
	ReconstructabilityStatus ModelRequestDebugResponseReconstructabilityStatus `json:"reconstructability_status"`
	Records                  []ModelRequestDebugRecord                         `json:"records"`
	RunId                    string                                            `json:"run_id"`
}

// ModelRequestDebugResponseReconstructabilityStatus defines model for ModelRequestDebugResponse.ReconstructabilityStatus.
type ModelRequestDebugResponseReconstructabilityStatus string

// ModelRequestEnvelope defines model for ModelRequestEnvelope.
type ModelRequestEnvelope struct {
	Attempt              int                     `json:"attempt"`
	ContextManifestId    *string                 `json:"context_manifest_id,omitempty"`
	ConversationId       string                  `json:"conversation_id"`
	CreatedAt            time.Time               `json:"created_at"`
	Id                   string                  `json:"id"`
	MessageCount         int                     `json:"message_count"`
	Model                string                  `json:"model"`
	ModelCallId          string                  `json:"model_call_id"`
	Operation            string                  `json:"operation"`
	Parameters           *map[string]interface{} `json:"parameters"`
	PayloadBytes         int                     `json:"payload_bytes"`
	PayloadHash          string                  `json:"payload_hash"`
	Provider             string                  `json:"provider"`
	RunId                string                  `json:"run_id"`
	RuntimeSnapshotHash  string                  `json:"runtime_snapshot_hash"`
	SourceTokenBreakdown *map[string]int         `json:"source_token_breakdown"`
	StageId              *string                 `json:"stage_id,omitempty"`
	ToolCount            int                     `json:"tool_count"`
	TurnId               *string                 `json:"turn_id,omitempty"`
}

// ModelRequestSourceDiff defines model for ModelRequestSourceDiff.
type ModelRequestSourceDiff struct {
	EnvelopeSelectedTokens map[string]int `json:"envelope_selected_tokens"`
	ManifestExcludedTokens map[string]int `json:"manifest_excluded_tokens"`
	ManifestSelectedTokens map[string]int `json:"manifest_selected_tokens"`
	MatchesEnvelope        bool           `json:"matches_envelope"`
}

// OperatorAttentionAction defines model for OperatorAttentionAction.
type OperatorAttentionAction struct {
	Enabled           bool    `json:"enabled"`
	Kind              string  `json:"kind"`
	Label             string  `json:"label"`
	TargetId          *string `json:"target_id,omitempty"`
	UnavailableReason *string `json:"unavailable_reason,omitempty"`
}

// OperatorAttentionEvidence defines model for OperatorAttentionEvidence.
type OperatorAttentionEvidence struct {
	ArtifactRefs *[]string `json:"artifact_refs,omitempty"`
	Id           *string   `json:"id,omitempty"`
	Kind         string    `json:"kind"`
	Status       *string   `json:"status,omitempty"`
	Summary      string    `json:"summary"`
}

// OperatorAttentionItem defines model for OperatorAttentionItem.
type OperatorAttentionItem struct {
	ConversationId      string                      `json:"conversation_id"`
	ConversationTitle   string                      `json:"conversation_title"`
	Evidence            []OperatorAttentionEvidence `json:"evidence"`
	Message             string                      `json:"message"`
	ObservationSequence int64                       `json:"observation_sequence"`
	Reason              OperatorAttentionItemReason `json:"reason"`
	RecommendedAction   *OperatorAttentionAction    `json:"recommended_action,omitempty"`
	RunId               string                      `json:"run_id"`
	RunStatus           RunStatus                   `json:"run_status"`
	Title               string                      `json:"title"`
	UpdatedAt           time.Time                   `json:"updated_at"`
}

// OperatorAttentionItemReason defines model for OperatorAttentionItem.Reason.
type OperatorAttentionItemReason string

// PartialOutput Bounded display replacement committed at an event sequence; never model continuation or a final Message.
type PartialOutput struct {
	Attempt     *int                 `json:"attempt,omitempty"`
	Channel     PartialOutputChannel `json:"channel"`
	ModelCallId *string              `json:"model_call_id,omitempty"`

	// Offset UTF-8 byte length of this display replacement
	Offset    int                 `json:"offset"`
	Revision  int64               `json:"revision"`
	Role      *string             `json:"role,omitempty"`
	Round     int                 `json:"round"`
	RunId     string              `json:"run_id"`
	Sequence  int64               `json:"sequence"`
	StageId   *string             `json:"stage_id,omitempty"`
	Status    PartialOutputStatus `json:"status"`
	Text      string              `json:"text"`
	Truncated *bool               `json:"truncated,omitempty"`
	TurnId    string              `json:"turn_id"`
}

// PartialOutputChannel defines model for PartialOutput.Channel.
type PartialOutputChannel string

// PartialOutputStatus defines model for PartialOutput.Status.
type PartialOutputStatus string

// RAGCitation defines model for RAGCitation.
type RAGCitation struct {
	ChunkId         string    `json:"chunk_id"`
	DocumentId      string    `json:"document_id"`
	DocumentTitle   string    `json:"document_title"`
	DocumentVersion *string   `json:"document_version,omitempty"`
	EndOffset       *int      `json:"end_offset,omitempty"`
	RunId           *string   `json:"run_id,omitempty"`
	SectionPath     *[]string `json:"section_path,omitempty"`
	SourceChunkIds  *[]string `json:"source_chunk_ids,omitempty"`
	SourceId        string    `json:"source_id"`
	StartOffset     *int      `json:"start_offset,omitempty"`
	ToolCallId      *string   `json:"tool_call_id,omitempty"`
	ToolEventId     *string   `json:"tool_event_id,omitempty"`
}

// RecoveryAction defines model for RecoveryAction.
type RecoveryAction struct {
	Enabled           bool    `json:"enabled"`
	Kind              string  `json:"kind"`
	Label             string  `json:"label"`
	TargetId          *string `json:"target_id,omitempty"`
	UnavailableReason *string `json:"unavailable_reason,omitempty"`
}

// RecoveryEvidence defines model for RecoveryEvidence.
type RecoveryEvidence struct {
	ArtifactRefs *[]string `json:"artifact_refs,omitempty"`
	Id           *string   `json:"id,omitempty"`
	Kind         string    `json:"kind"`
	Status       *string   `json:"status,omitempty"`
	Summary      string    `json:"summary"`
}

// RecoverySummary defines model for RecoverySummary.
type RecoverySummary struct {
	Actions      *[]RecoveryAction   `json:"actions"`
	ArtifactRefs *[]string           `json:"artifact_refs"`
	Evidence     *[]RecoveryEvidence `json:"evidence"`
	Message      string              `json:"message"`
	Reason       string              `json:"reason"`
	Title        string              `json:"title"`
}

// ResumeRunRequest defines model for ResumeRunRequest.
type ResumeRunRequest struct {
	UserInput string `json:"user_input"`
}

// Run defines model for Run.
type Run struct {
	ActiveRuntimeMs    int64               `json:"active_runtime_ms"`
	AgentId            string              `json:"agent_id"`
	CompletedAt        *time.Time          `json:"completed_at,omitempty"`
	CompletionContract *CompletionContract `json:"completion_contract,omitempty"`
	ConversationId     string              `json:"conversation_id"`
	CreatedAt          time.Time           `json:"created_at"`
	Error              *string             `json:"error,omitempty"`
	ExecutionStartedAt *time.Time          `json:"execution_started_at,omitempty"`
	HeartbeatAt        *time.Time          `json:"heartbeat_at,omitempty"`
	Id                 string              `json:"id"`
	StartedAt          *time.Time          `json:"started_at,omitempty"`
	Status             RunStatus           `json:"status"`
	UpdatedAt          time.Time           `json:"updated_at"`
	VerificationStatus VerificationStatus  `json:"verification_status"`
	WorkspaceId        string              `json:"workspace_id"`
}

// RunEvent defines model for RunEvent.
type RunEvent struct {
	ConversationId *string                `json:"conversation_id,omitempty"`
	Id             string                 `json:"id"`
	ParentEventId  *string                `json:"parent_event_id,omitempty"`
	Payload        map[string]interface{} `json:"payload"`
	RunId          string                 `json:"run_id"`
	SchemaVersion  int                    `json:"schema_version"`
	Sequence       int64                  `json:"sequence"`
	StageId        *string                `json:"stage_id,omitempty"`
	Timestamp      time.Time              `json:"timestamp"`
	TurnId         *string                `json:"turn_id,omitempty"`
	Type           string                 `json:"type"`
}

// RunInput defines model for RunInput.
type RunInput struct {
	AgentId        string         `json:"agent_id"`
	AppliedAt      *time.Time     `json:"applied_at,omitempty"`
	AppliedRunId   string         `json:"applied_run_id"`
	Content        string         `json:"content"`
	ConversationId string         `json:"conversation_id"`
	CreatedAt      time.Time      `json:"created_at"`
	ExpiresAt      time.Time      `json:"expires_at"`
	Id             string         `json:"id"`
	Kind           RunInputKind   `json:"kind"`
	Mode           ChatMode       `json:"mode"`
	RunId          string         `json:"run_id"`
	StageId        string         `json:"stage_id"`
	Status         RunInputStatus `json:"status"`
	TurnId         string         `json:"turn_id"`
}

// RunInputKind defines model for RunInput.Kind.
type RunInputKind string

// RunInputStatus defines model for RunInput.Status.
type RunInputStatus string

// RunInputRequest defines model for RunInputRequest.
type RunInputRequest struct {
	AgentId        *string             `json:"agent_id,omitempty"`
	Content        string              `json:"content"`
	IdempotencyKey string              `json:"idempotency_key"`
	Kind           RunInputRequestKind `json:"kind"`
	Mode           *ChatMode           `json:"mode,omitempty"`
	RunId          string              `json:"run_id"`
}

// RunInputRequestKind defines model for RunInputRequest.Kind.
type RunInputRequestKind string

// RunProjection defines model for RunProjection.
type RunProjection struct {
	ActiveModelCallIds *[]string `json:"active_model_call_ids"`
	ActiveStageIds     *[]string `json:"active_stage_ids"`
	ActiveToolCallIds  *[]string `json:"active_tool_call_ids"`
	ActiveTurnIds      *[]string `json:"active_turn_ids"`
	AsOfSequence       int64     `json:"as_of_sequence"`
	ConversationId     string    `json:"conversation_id"`
	RunId              string    `json:"run_id"`

	// Status Durable status; read views tolerate historical values.
	Status             string          `json:"status"`
	Summary            RunTraceSummary `json:"summary"`
	VerificationStatus string          `json:"verification_status"`
}

// RunProjectionSnapshot defines model for RunProjectionSnapshot.
type RunProjectionSnapshot struct {
	AsOfSequence      int64                      `json:"as_of_sequence"`
	InvariantFailures *[]RuntimeInvariantFailure `json:"invariant_failures"`
	PartialOutputs    *[]PartialOutput           `json:"partial_outputs"`
	Run               RunProjection              `json:"run"`
	SkillEvidence     *[]SkillEvidence           `json:"skill_evidence,omitempty"`
	ToolProgress      *[]ToolProgress            `json:"tool_progress"`
	Usage             UsageProjection            `json:"usage"`
	Verification      VerificationProjection     `json:"verification"`
}

// RunReplay defines model for RunReplay.
type RunReplay struct {
	Conversation          Conversation            `json:"conversation"`
	Messages              *[]Message              `json:"messages"`
	Projection            RunProjectionSnapshot   `json:"projection"`
	RecoverySummary       *RecoverySummary        `json:"recovery_summary,omitempty"`
	Run                   Run                     `json:"run"`
	RunEvents             *[]RunEvent             `json:"run_events"`
	RuntimeSnapshot       *map[string]interface{} `json:"runtime_snapshot,omitempty"`
	StageCheckpoints      *[]StageCheckpoint      `json:"stage_checkpoints"`
	Steps                 *[]CollaborationStep    `json:"steps"`
	Summary               RunTraceSummary         `json:"summary"`
	TaskStateRevisions    *[]TaskStateRevision    `json:"task_state_revisions"`
	ToolArtifacts         *[]ToolArtifact         `json:"tool_artifacts"`
	ToolEffects           *[]ToolEffect           `json:"tool_effects"`
	UsageLedger           RunUsageLedger          `json:"usage_ledger"`
	VerificationArtifacts *[]VerificationArtifact `json:"verification_artifacts"`
	VerificationEvidence  *[]VerificationEvidence `json:"verification_evidence"`
}

// RunStatus defines model for RunStatus.
type RunStatus string

// RunTraceSummary defines model for RunTraceSummary.
type RunTraceSummary struct {
	CompletionTokens    int       `json:"completion_tokens"`
	ErrorCount          int       `json:"error_count"`
	LlmCalls            int       `json:"llm_calls"`
	PromptTokens        int       `json:"prompt_tokens"`
	RunId               string    `json:"run_id"`
	Status              RunStatus `json:"status"`
	TokenUsageEstimated bool      `json:"token_usage_estimated"`
	ToolCalls           int       `json:"tool_calls"`
	TotalDurationMs     int64     `json:"total_duration_ms"`
	TotalTokens         int       `json:"total_tokens"`
}

// RunUsageEntry defines model for RunUsageEntry.
type RunUsageEntry struct {
	// Breakdown Optional provider-reported subsets, already included in prompt/completion totals. Absent is unknown, not zero.
	Breakdown        *UsageBreakdown `json:"breakdown,omitempty"`
	CompletionTokens *int            `json:"completion_tokens,omitempty"`

	// CostDetails Frozen quote and settlement assumptions; an estimate, not a provider invoice.
	CostDetails         *UsageCostDetails    `json:"cost_details,omitempty"`
	Estimated           *bool                `json:"estimated,omitempty"`
	EstimatedCostMicros *int64               `json:"estimated_cost_micros,omitempty"`
	Id                  string               `json:"id"`
	Kind                RunUsageEntryKind    `json:"kind"`
	Model               *string              `json:"model,omitempty"`
	ModelCalls          *int                 `json:"model_calls,omitempty"`
	OperationId         string               `json:"operation_id"`
	PromptTokens        *int                 `json:"prompt_tokens,omitempty"`
	Purpose             RunUsageEntryPurpose `json:"purpose"`
	RunId               string               `json:"run_id"`
	StageId             *string              `json:"stage_id,omitempty"`
	Timestamp           time.Time            `json:"timestamp"`
	ToolCalls           *int                 `json:"tool_calls,omitempty"`
	ToolName            *string              `json:"tool_name,omitempty"`
	TotalTokens         *int                 `json:"total_tokens,omitempty"`
	TurnId              *string              `json:"turn_id,omitempty"`
}

// RunUsageEntryKind defines model for RunUsageEntry.Kind.
type RunUsageEntryKind string

// RunUsageEntryPurpose defines model for RunUsageEntry.Purpose.
type RunUsageEntryPurpose string

// RunUsageLedger defines model for RunUsageLedger.
type RunUsageLedger struct {
	Budget    RuntimeRunBudget `json:"budget"`
	Entries   *[]RunUsageEntry `json:"entries"`
	RunId     string           `json:"run_id"`
	Totals    RunUsageTotals   `json:"totals"`
	UpdatedAt *time.Time       `json:"updated_at,omitempty"`
}

// RunUsageTotals defines model for RunUsageTotals.
type RunUsageTotals struct {
	CompletionTokens    int   `json:"completion_tokens"`
	CostUnknownEntries  *int  `json:"cost_unknown_entries,omitempty"`
	EstimatedCostMicros int64 `json:"estimated_cost_micros"`
	ModelCalls          int   `json:"model_calls"`
	OpenReservations    int   `json:"open_reservations"`
	PromptTokens        int   `json:"prompt_tokens"`
	ToolCalls           int   `json:"tool_calls"`
	TotalTokens         int   `json:"total_tokens"`
}

// RuntimeInvariantFailure defines model for RuntimeInvariantFailure.
type RuntimeInvariantFailure struct {
	Code     string  `json:"code"`
	EventId  *string `json:"event_id,omitempty"`
	Message  string  `json:"message"`
	Owner    string  `json:"owner"`
	RunId    string  `json:"run_id"`
	Sequence *int64  `json:"sequence,omitempty"`
}

// RuntimeRunBudget defines model for RuntimeRunBudget.
type RuntimeRunBudget struct {
	InputCostPerMillionTokensMicros  *int64 `json:"input_cost_per_million_tokens_micros,omitempty"`
	MaxCompletionTokens              *int   `json:"max_completion_tokens,omitempty"`
	MaxEstimatedCostMicros           *int64 `json:"max_estimated_cost_micros,omitempty"`
	MaxModelCalls                    *int   `json:"max_model_calls,omitempty"`
	MaxPromptTokens                  *int   `json:"max_prompt_tokens,omitempty"`
	MaxRuntimeMs                     *int64 `json:"max_runtime_ms,omitempty"`
	MaxToolCalls                     *int   `json:"max_tool_calls,omitempty"`
	MaxTotalTokens                   *int   `json:"max_total_tokens,omitempty"`
	OutputCostPerMillionTokensMicros *int64 `json:"output_cost_per_million_tokens_micros,omitempty"`
}

// SkillEvidence defines model for SkillEvidence.
type SkillEvidence struct {
	Activation           SkillEvidenceActivation   `json:"activation"`
	AgentId              string                    `json:"agent_id"`
	Bound                bool                      `json:"bound"`
	EstimatedTokens      *int                      `json:"estimated_tokens,omitempty"`
	EventId              *string                   `json:"event_id,omitempty"`
	Failures             []SkillFailureEvidence    `json:"failures"`
	FirstRequestSequence *int64                    `json:"first_request_sequence,omitempty"`
	FirstSequence        *int64                    `json:"first_sequence,omitempty"`
	Hash                 string                    `json:"hash"`
	Instructions         SkillEvidenceInstructions `json:"instructions"`
	ManifestId           *string                   `json:"manifest_id,omitempty"`
	Name                 string                    `json:"name"`
	RequestId            *string                   `json:"request_id,omitempty"`
	Resources            []SkillResourceEvidence   `json:"resources"`
	StageId              *string                   `json:"stage_id,omitempty"`
}

// SkillEvidenceActivation defines model for SkillEvidence.Activation.
type SkillEvidenceActivation string

// SkillEvidenceInstructions defines model for SkillEvidence.Instructions.
type SkillEvidenceInstructions string

// SkillFailureEvidence defines model for SkillFailureEvidence.
type SkillFailureEvidence struct {
	Code     string  `json:"code"`
	EventId  string  `json:"event_id"`
	Path     *string `json:"path,omitempty"`
	Sequence int64   `json:"sequence"`
	Tool     string  `json:"tool"`
}

// SkillMetadata defines model for SkillMetadata.
type SkillMetadata struct {
	Description   string    `json:"description"`
	Hash          string    `json:"hash"`
	Name          string    `json:"name"`
	RequiredTools *[]string `json:"required_tools,omitempty"`
}

// SkillResourceEvidence defines model for SkillResourceEvidence.
type SkillResourceEvidence struct {
	EventId    string `json:"event_id"`
	Hash       string `json:"hash"`
	NextOffset int    `json:"next_offset"`
	Offset     int    `json:"offset"`
	Path       string `json:"path"`
	Sequence   int64  `json:"sequence"`
	TotalBytes int    `json:"total_bytes"`
}

// StageCheckpoint defines model for StageCheckpoint.
type StageCheckpoint struct {
	ConversationId      string    `json:"conversation_id"`
	CreatedAt           time.Time `json:"created_at"`
	Error               *string   `json:"error,omitempty"`
	EventCursor         int64     `json:"event_cursor"`
	Id                  string    `json:"id"`
	InputHash           string    `json:"input_hash"`
	OutputHash          *string   `json:"output_hash,omitempty"`
	Provider            string    `json:"provider"`
	RunId               string    `json:"run_id"`
	RuntimeSnapshotHash string    `json:"runtime_snapshot_hash"`
	StageId             string    `json:"stage_id"`
	Status              string    `json:"status"`
	ToolDefinitionsHash string    `json:"tool_definitions_hash"`
	UpdatedAt           time.Time `json:"updated_at"`
}

// TaskBlocker defines model for TaskBlocker.
type TaskBlocker struct {
	Description string            `json:"description"`
	Id          string            `json:"id"`
	Status      TaskBlockerStatus `json:"status"`
}

// TaskBlockerStatus defines model for TaskBlockerStatus.
type TaskBlockerStatus string

// TaskConstraint defines model for TaskConstraint.
type TaskConstraint struct {
	Id        string `json:"id"`
	Statement string `json:"statement"`
}

// TaskDecision defines model for TaskDecision.
type TaskDecision struct {
	Id           string  `json:"id"`
	Rationale    *string `json:"rationale,omitempty"`
	Statement    string  `json:"statement"`
	SupersedesId *string `json:"supersedes_id,omitempty"`
}

// TaskItem defines model for TaskItem.
type TaskItem struct {
	ArtifactRefs *[]string      `json:"artifact_refs,omitempty"`
	Details      *string        `json:"details,omitempty"`
	Id           string         `json:"id"`
	Status       TaskItemStatus `json:"status"`
	Title        string         `json:"title"`
}

// TaskItemStatus defines model for TaskItemStatus.
type TaskItemStatus string

// TaskState defines model for TaskState.
type TaskState struct {
	ArtifactRefs   []string         `json:"artifact_refs"`
	Blockers       []TaskBlocker    `json:"blockers"`
	Constraints    []TaskConstraint `json:"constraints"`
	ConversationId string           `json:"conversation_id"`
	Decisions      []TaskDecision   `json:"decisions"`
	Goal           *string          `json:"goal,omitempty"`
	SchemaVersion  int              `json:"schema_version"`
	Tasks          []TaskItem       `json:"tasks"`
	UpdatedAt      time.Time        `json:"updated_at"`
	Version        int64            `json:"version"`
	WorkspaceId    string           `json:"workspace_id"`
}

// TaskStateOperation Closed command names; operation-specific required fields are validated by the domain patch executor.
type TaskStateOperation struct {
	ArtifactRef  *string                `json:"artifact_ref,omitempty"`
	Blocker      *TaskBlocker           `json:"blocker,omitempty"`
	BlockerId    *string                `json:"blocker_id,omitempty"`
	Constraint   *TaskConstraint        `json:"constraint,omitempty"`
	ConstraintId *string                `json:"constraint_id,omitempty"`
	Decision     *TaskDecision          `json:"decision,omitempty"`
	Goal         *string                `json:"goal,omitempty"`
	Task         *TaskItem              `json:"task,omitempty"`
	TaskId       *string                `json:"task_id,omitempty"`
	TaskStatus   *TaskItemStatus        `json:"task_status,omitempty"`
	Type         TaskStateOperationType `json:"type"`
}

// TaskStateOperationType defines model for TaskStateOperation.Type.
type TaskStateOperationType string

// TaskStatePatch defines model for TaskStatePatch.
type TaskStatePatch struct {
	ExpectedVersion int64                `json:"expected_version"`
	Operations      []TaskStateOperation `json:"operations"`
}

// TaskStateRevision defines model for TaskStateRevision.
type TaskStateRevision struct {
	ConversationId  string          `json:"conversation_id"`
	CreatedAt       time.Time       `json:"created_at"`
	Id              string          `json:"id"`
	Patch           TaskStatePatch  `json:"patch"`
	PreviousVersion int64           `json:"previous_version"`
	Source          TaskStateSource `json:"source"`
	State           TaskState       `json:"state"`
	Version         int64           `json:"version"`
	WorkspaceId     string          `json:"workspace_id"`
}

// TaskStateSource defines model for TaskStateSource.
type TaskStateSource struct {
	ActorId         *string `json:"actor_id,omitempty"`
	ActorType       string  `json:"actor_type"`
	RunId           *string `json:"run_id,omitempty"`
	SourceMessageId *string `json:"source_message_id,omitempty"`
	StageId         *string `json:"stage_id,omitempty"`
	TurnId          *string `json:"turn_id,omitempty"`
}

// ToolArtifact defines model for ToolArtifact.
type ToolArtifact struct {
	ContentHash        string     `json:"content_hash"`
	CreatedAt          time.Time  `json:"created_at"`
	DefinitionRevision *string    `json:"definition_revision,omitempty"`
	Expired            *bool      `json:"expired,omitempty"`
	ExpiresAt          *time.Time `json:"expires_at,omitempty"`
	Id                 string     `json:"id"`
	MediaType          string     `json:"media_type"`
	OriginalByteSize   int        `json:"original_byte_size"`
	Redacted           bool       `json:"redacted"`
	RedactionCount     int        `json:"redaction_count"`
	RedactionStrategy  *string    `json:"redaction_strategy,omitempty"`
	RunId              string     `json:"run_id"`
	SchemaVersion      int        `json:"schema_version"`
	StageId            *string    `json:"stage_id,omitempty"`
	StoredByteSize     int        `json:"stored_byte_size"`
	ToolCallId         string     `json:"tool_call_id"`
	ToolName           string     `json:"tool_name"`
	TurnId             *string    `json:"turn_id,omitempty"`
}

// ToolEffect defines model for ToolEffect.
type ToolEffect struct {
	AvailableActions   *[]ToolEffectReconciliationAction `json:"available_actions,omitempty"`
	CreatedAt          time.Time                         `json:"created_at"`
	DefinitionRevision *string                           `json:"definition_revision,omitempty"`
	Error              *string                           `json:"error,omitempty"`
	HasResult          bool                              `json:"has_result"`
	IdempotencyKey     string                            `json:"idempotency_key"`
	RequestHash        string                            `json:"request_hash"`
	RunId              string                            `json:"run_id"`
	StageId            string                            `json:"stage_id"`
	Status             string                            `json:"status"`
	ToolCallId         string                            `json:"tool_call_id"`
	ToolName           string                            `json:"tool_name"`
	TurnId             *string                           `json:"turn_id,omitempty"`
	UpdatedAt          time.Time                         `json:"updated_at"`
	Version            int64                             `json:"version"`
}

// ToolEffectList defines model for ToolEffectList.
type ToolEffectList struct {
	Effects []ToolEffect `json:"effects"`
	RunId   string       `json:"run_id"`
}

// ToolEffectReconciliationAction defines model for ToolEffectReconciliationAction.
type ToolEffectReconciliationAction string

// ToolEffectReconciliationCommand defines model for ToolEffectReconciliationCommand.
type ToolEffectReconciliationCommand struct {
	Action          ToolEffectReconciliationAction `json:"action"`
	Actor           string                         `json:"actor"`
	CommandId       string                         `json:"command_id"`
	ExpectedVersion int64                          `json:"expected_version"`
	Reason          string                         `json:"reason"`
	Result          interface{}                    `json:"result,omitempty"`
}

// ToolEffectReconciliationOutcome defines model for ToolEffectReconciliationOutcome.
type ToolEffectReconciliationOutcome struct {
	Applied   bool       `json:"applied"`
	CommandId string     `json:"command_id"`
	Effect    ToolEffect `json:"effect"`
	Outcome   string     `json:"outcome"`
}

// ToolInfo defines model for ToolInfo.
type ToolInfo struct {
	ConfigRevision *int64 `json:"config_revision,omitempty"`
	Description    string `json:"description"`
	Enabled        bool   `json:"enabled"`

	// ExcludedReason Service, prerequisite, Workspace or static-policy exclusion reason; argument-dependent decisions remain in Run events.
	ExcludedReason *string                `json:"excluded_reason,omitempty"`
	Name           string                 `json:"name"`
	Parameters     map[string]interface{} `json:"parameters"`

	// ServiceEnabled Operator-owned service switch. Workspace owners cannot override it.
	ServiceEnabled *bool `json:"service_enabled,omitempty"`

	// UnavailableReason Runtime prerequisite that prevents an enabled Tool from being offered to the model.
	UnavailableReason *string `json:"unavailable_reason,omitempty"`

	// WorkspaceEnabled Persisted Workspace allowlist entry, independent of service readiness.
	WorkspaceEnabled *bool `json:"workspace_enabled,omitempty"`
}

// ToolProgress defines model for ToolProgress.
type ToolProgress struct {
	Completed *int64 `json:"completed,omitempty"`

	// Message Backend enforces a 1024 UTF-8 byte cap after redaction.
	Message    *string            `json:"message,omitempty"`
	Phase      string             `json:"phase"`
	RunId      string             `json:"run_id"`
	Sequence   int64              `json:"sequence"`
	StageId    *string            `json:"stage_id,omitempty"`
	Status     ToolProgressStatus `json:"status"`
	ToolCallId string             `json:"tool_call_id"`
	ToolName   string             `json:"tool_name"`
	Total      *int64             `json:"total,omitempty"`
	Truncated  *bool              `json:"truncated,omitempty"`
	TurnId     string             `json:"turn_id"`
}

// ToolProgressStatus defines model for ToolProgress.Status.
type ToolProgressStatus string

// ToolProgressUpdate Bounded semantic progress only; counts do not imply Tool completion.
type ToolProgressUpdate struct {
	Completed *int64 `json:"completed,omitempty"`

	// Message Backend enforces a 1024 UTF-8 byte cap after redaction.
	Message   *string `json:"message,omitempty"`
	Phase     string  `json:"phase"`
	Total     *int64  `json:"total,omitempty"`
	Truncated *bool   `json:"truncated,omitempty"`
}

// UpdateConversationRequest defines model for UpdateConversationRequest.
type UpdateConversationRequest struct {
	Title string `json:"title"`
}

// UsageBreakdown Optional provider-reported subsets, already included in prompt/completion totals. Absent is unknown, not zero.
type UsageBreakdown struct {
	CachedInputTokens *int                 `json:"cached_input_tokens,omitempty"`
	ReasoningTokens   *int                 `json:"reasoning_tokens,omitempty"`
	Source            UsageBreakdownSource `json:"source"`
}

// UsageBreakdownSource defines model for UsageBreakdown.Source.
type UsageBreakdownSource string

// UsageCostDetails Frozen quote and settlement assumptions; an estimate, not a provider invoice.
type UsageCostDetails struct {
	CacheDiscountApplied bool                   `json:"cache_discount_applied"`
	Pricing              UsagePricing           `json:"pricing"`
	Reason               string                 `json:"reason"`
	Status               UsageCostDetailsStatus `json:"status"`
}

// UsageCostDetailsStatus defines model for UsageCostDetails.Status.
type UsageCostDetailsStatus string

// UsagePricing defines model for UsagePricing.
type UsagePricing struct {
	CachedInputPerMillionTokensMicros *int64 `json:"cached_input_per_million_tokens_micros,omitempty"`
	InputPerMillionTokensMicros       int64  `json:"input_per_million_tokens_micros"`
	OutputPerMillionTokensMicros      int64  `json:"output_per_million_tokens_micros"`
	Source                            string `json:"source"`
}

// UsageProjection defines model for UsageProjection.
type UsageProjection struct {
	AsOfSequence int64          `json:"as_of_sequence"`
	Ledger       RunUsageLedger `json:"ledger"`
}

// VerificationArtifact defines model for VerificationArtifact.
type VerificationArtifact struct {
	EvidenceId           string                 `json:"evidence_id"`
	Id                   string                 `json:"id"`
	Kind                 string                 `json:"kind"`
	RunId                string                 `json:"run_id"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// VerificationDecision defines model for VerificationDecision.
type VerificationDecision struct {
	AllowCompletion bool               `json:"allow_completion"`
	Attempt         int                `json:"attempt"`
	RunStatus       RunStatus          `json:"run_status"`
	Status          VerificationStatus `json:"status"`
	SubjectHash     string             `json:"subject_hash"`
	Summary         string             `json:"summary"`
}

// VerificationEvidence defines model for VerificationEvidence.
type VerificationEvidence struct {
	Id                   string                 `json:"id"`
	RunId                string                 `json:"run_id"`
	Status               VerificationStatus     `json:"status"`
	VerifierId           string                 `json:"verifier_id"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// VerificationPolicyInput defines model for VerificationPolicyInput.
type VerificationPolicyInput struct {
	MaxAttempts int                                `json:"max_attempts"`
	Mode        VerificationPolicyInputMode        `json:"mode"`
	OnExhausted VerificationPolicyInputOnExhausted `json:"on_exhausted"`
}

// VerificationPolicyInputMode defines model for VerificationPolicyInput.Mode.
type VerificationPolicyInputMode string

// VerificationPolicyInputOnExhausted defines model for VerificationPolicyInput.OnExhausted.
type VerificationPolicyInputOnExhausted string

// VerificationProjection defines model for VerificationProjection.
type VerificationProjection struct {
	AsOfSequence       int64   `json:"as_of_sequence"`
	CurrentSubjectHash *string `json:"current_subject_hash,omitempty"`
	EvidenceCount      int     `json:"evidence_count"`
	FreshEvidenceCount int     `json:"fresh_evidence_count"`
	LatestAttempt      int     `json:"latest_attempt"`
	Status             string  `json:"status"`
}

// VerificationStatus defines model for VerificationStatus.
type VerificationStatus string

// VerifierSpecInput defines model for VerifierSpecInput.
type VerifierSpecInput struct {
	Config    map[string]interface{} `json:"config"`
	Id        string                 `json:"id"`
	Required  bool                   `json:"required"`
	TimeoutMs *int64                 `json:"timeout_ms,omitempty"`
	Type      VerifierType           `json:"type"`
	Version   *string                `json:"version,omitempty"`
}

// VerifierType defines model for VerifierType.
type VerifierType string

// VerifyRunResponse defines model for VerifyRunResponse.
type VerifyRunResponse struct {
	Decision VerificationDecision `json:"decision"`
	Run      Run                  `json:"run"`
}

// WebCitation defines model for WebCitation.
type WebCitation struct {
	RunId       string `json:"run_id"`
	SourceId    string `json:"source_id"`
	Title       string `json:"title"`
	ToolCallId  string `json:"tool_call_id"`
	ToolEventId string `json:"tool_event_id"`
	Url         string `json:"url"`
}

// Workspace defines model for Workspace.
type Workspace struct {
	CreatedAt   time.Time  `json:"created_at"`
	DeletedAt   *time.Time `json:"deleted_at,omitempty"`
	Description string     `json:"description"`

	// Id Decimal BIGINT identity encoded as a string to preserve precision.
	Id          string          `json:"id"`
	IsDefault   bool            `json:"is_default"`
	Name        string          `json:"name"`
	OwnerUserId string          `json:"owner_user_id"`
	Status      WorkspaceStatus `json:"status"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

// WorkspaceStatus defines model for Workspace.Status.
type WorkspaceStatus string

// WorkspaceCreateRequest defines model for WorkspaceCreateRequest.
type WorkspaceCreateRequest struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// WorkspaceUpdateRequest defines model for WorkspaceUpdateRequest.
type WorkspaceUpdateRequest struct {
	Description            *string                       `json:"description,omitempty"`
	MakeDefault            *bool                         `json:"make_default,omitempty"`
	Name                   *string                       `json:"name,omitempty"`
	ReplacementWorkspaceId *string                       `json:"replacement_workspace_id,omitempty"`
	Status                 *WorkspaceUpdateRequestStatus `json:"status,omitempty"`
}

// WorkspaceUpdateRequestStatus defines model for WorkspaceUpdateRequest.Status.
type WorkspaceUpdateRequestStatus string

// AgentId defines model for AgentId.
type AgentId = string

// ConversationId defines model for ConversationId.
type ConversationId = string

// RunId defines model for RunId.
type RunId = string

// ToolName defines model for ToolName.
type ToolName = string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = ErrorResponse

// CompleteLoginParams defines parameters for CompleteLogin.
type CompleteLoginParams struct {
	Code  *string `form:"code,omitempty" json:"code,omitempty"`
	State *string `form:"state,omitempty" json:"state,omitempty"`
}

// ObserveRunEventsParams defines parameters for ObserveRunEvents.
type ObserveRunEventsParams struct {
	// After Resume after this durable Run event sequence.
	After *int64 `form:"after,omitempty" json:"after,omitempty"`

	// LastEventID SSE resume cursor; takes precedence over the after query parameter.
	LastEventID *int64 `json:"Last-Event-ID,omitempty"`
}

// GetRunModelRequestsParams defines parameters for GetRunModelRequests.
type GetRunModelRequestsParams struct {
	// IncludeContent Return captured content only when retained by the configured capture policy.
	IncludeContent *bool `form:"include_content,omitempty" json:"include_content,omitempty"`
}

// ListToolEffectsParams defines parameters for ListToolEffects.
type ListToolEffectsParams struct {
	Status *string `form:"status,omitempty" json:"status,omitempty"`
	Tool   *string `form:"tool,omitempty" json:"tool,omitempty"`
}

// DeleteWorkspaceParams defines parameters for DeleteWorkspace.
type DeleteWorkspaceParams struct {
	ReplacementWorkspaceId *string `form:"replacement_workspace_id,omitempty" json:"replacement_workspace_id,omitempty"`
}

// CreateAgentJSONRequestBody defines body for CreateAgent for application/json ContentType.
type CreateAgentJSONRequestBody = AgentConfigRequest

// UpdateAgentJSONRequestBody defines body for UpdateAgent for application/json ContentType.
type UpdateAgentJSONRequestBody = AgentConfigRequest

// StreamChatJSONRequestBody defines body for StreamChat for application/json ContentType.
type StreamChatJSONRequestBody = ChatRequest

// CreateConversationJSONRequestBody defines body for CreateConversation for application/json ContentType.
type CreateConversationJSONRequestBody = CreateConversationRequest

// UpdateConversationJSONRequestBody defines body for UpdateConversation for application/json ContentType.
type UpdateConversationJSONRequestBody = UpdateConversationRequest

// EnqueueRunInputJSONRequestBody defines body for EnqueueRunInput for application/json ContentType.
type EnqueueRunInputJSONRequestBody = RunInputRequest

// PatchTaskStateJSONRequestBody defines body for PatchTaskState for application/json ContentType.
type PatchTaskStateJSONRequestBody = TaskStatePatch

// ContinueRunJSONRequestBody defines body for ContinueRun for application/json ContentType.
type ContinueRunJSONRequestBody = ContinueRunRequest

// ResumeRunJSONRequestBody defines body for ResumeRun for application/json ContentType.
type ResumeRunJSONRequestBody = ResumeRunRequest

// ReconcileToolEffectJSONRequestBody defines body for ReconcileToolEffect for application/json ContentType.
type ReconcileToolEffectJSONRequestBody = ToolEffectReconciliationCommand

// CreateWorkspaceJSONRequestBody defines body for CreateWorkspace for application/json ContentType.
type CreateWorkspaceJSONRequestBody = WorkspaceCreateRequest

// UpdateWorkspaceJSONRequestBody defines body for UpdateWorkspace for application/json ContentType.
type UpdateWorkspaceJSONRequestBody = WorkspaceUpdateRequest

// Getter for additional properties for VerificationArtifact. Returns the specified
// element and whether it was found
func (a VerificationArtifact) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for VerificationArtifact
func (a *VerificationArtifact) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for VerificationArtifact to handle AdditionalProperties
func (a *VerificationArtifact) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["evidence_id"]; found {
		err = json.Unmarshal(raw, &a.EvidenceId)
		if err != nil {
			return fmt.Errorf("error reading 'evidence_id': %w", err)
		}
		delete(object, "evidence_id")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["kind"]; found {
		err = json.Unmarshal(raw, &a.Kind)
		if err != nil {
			return fmt.Errorf("error reading 'kind': %w", err)
		}
		delete(object, "kind")
	}

	if raw, found := object["run_id"]; found {
		err = json.Unmarshal(raw, &a.RunId)
		if err != nil {
			return fmt.Errorf("error reading 'run_id': %w", err)
		}
		delete(object, "run_id")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for VerificationArtifact to handle AdditionalProperties
func (a VerificationArtifact) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["evidence_id"], err = json.Marshal(a.EvidenceId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'evidence_id': %w", err)
	}

	object["id"], err = json.Marshal(a.Id)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'id': %w", err)
	}

	object["kind"], err = json.Marshal(a.Kind)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'kind': %w", err)
	}

	object["run_id"], err = json.Marshal(a.RunId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'run_id': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for VerificationEvidence. Returns the specified
// element and whether it was found
func (a VerificationEvidence) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for VerificationEvidence
func (a *VerificationEvidence) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for VerificationEvidence to handle AdditionalProperties
func (a *VerificationEvidence) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["run_id"]; found {
		err = json.Unmarshal(raw, &a.RunId)
		if err != nil {
			return fmt.Errorf("error reading 'run_id': %w", err)
		}
		delete(object, "run_id")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["verifier_id"]; found {
		err = json.Unmarshal(raw, &a.VerifierId)
		if err != nil {
			return fmt.Errorf("error reading 'verifier_id': %w", err)
		}
		delete(object, "verifier_id")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for VerificationEvidence to handle AdditionalProperties
func (a VerificationEvidence) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["id"], err = json.Marshal(a.Id)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'id': %w", err)
	}

	object["run_id"], err = json.Marshal(a.RunId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'run_id': %w", err)
	}

	object["status"], err = json.Marshal(a.Status)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'status': %w", err)
	}

	object["verifier_id"], err = json.Marshal(a.VerifierId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'verifier_id': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
