// Package apicontract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apicontract

import (
	"encoding/json"
	"fmt"
	"time"
)

// Defines values for ChatExecutor.
const (
	Langchaingo ChatExecutor = "langchaingo"
	Native      ChatExecutor = "native"
)

// Valid indicates whether the value is a known member of the ChatExecutor enum.
func (e ChatExecutor) Valid() bool {
	switch e {
	case Langchaingo:
		return true
	case Native:
		return true
	default:
		return false
	}
}

// Defines values for ChatMode.
const (
	Autonomous ChatMode = "autonomous"
	MultiAgent ChatMode = "multi_agent"
	Single     ChatMode = "single"
)

// Valid indicates whether the value is a known member of the ChatMode enum.
func (e ChatMode) Valid() bool {
	switch e {
	case Autonomous:
		return true
	case MultiAgent:
		return true
	case Single:
		return true
	default:
		return false
	}
}

// Defines values for CollaborationStepStatus.
const (
	CollaborationStepStatusCompleted CollaborationStepStatus = "completed"
	CollaborationStepStatusFailed    CollaborationStepStatus = "failed"
	CollaborationStepStatusQueued    CollaborationStepStatus = "queued"
	CollaborationStepStatusRunning   CollaborationStepStatus = "running"
)

// Valid indicates whether the value is a known member of the CollaborationStepStatus enum.
func (e CollaborationStepStatus) Valid() bool {
	switch e {
	case CollaborationStepStatusCompleted:
		return true
	case CollaborationStepStatusFailed:
		return true
	case CollaborationStepStatusQueued:
		return true
	case CollaborationStepStatusRunning:
		return true
	default:
		return false
	}
}

// Defines values for CompletionContractSubjectType.
const (
	CompletionContractSubjectTypeRunOutput CompletionContractSubjectType = "run_output"
)

// Valid indicates whether the value is a known member of the CompletionContractSubjectType enum.
func (e CompletionContractSubjectType) Valid() bool {
	switch e {
	case CompletionContractSubjectTypeRunOutput:
		return true
	default:
		return false
	}
}

// Defines values for CompletionContractInputSubjectType.
const (
	CompletionContractInputSubjectTypeRunOutput CompletionContractInputSubjectType = "run_output"
)

// Valid indicates whether the value is a known member of the CompletionContractInputSubjectType enum.
func (e CompletionContractInputSubjectType) Valid() bool {
	switch e {
	case CompletionContractInputSubjectTypeRunOutput:
		return true
	default:
		return false
	}
}

// Defines values for MessageRole.
const (
	Assistant MessageRole = "assistant"
	System    MessageRole = "system"
	User      MessageRole = "user"
)

// Valid indicates whether the value is a known member of the MessageRole enum.
func (e MessageRole) Valid() bool {
	switch e {
	case Assistant:
		return true
	case System:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for RunStatus.
const (
	RunStatusCanceled          RunStatus = "canceled"
	RunStatusCanceling         RunStatus = "canceling"
	RunStatusCompleted         RunStatus = "completed"
	RunStatusFailed            RunStatus = "failed"
	RunStatusFailedRecoverable RunStatus = "failed_recoverable"
	RunStatusQueued            RunStatus = "queued"
	RunStatusRunning           RunStatus = "running"
	RunStatusWaitingForUser    RunStatus = "waiting_for_user"
)

// Valid indicates whether the value is a known member of the RunStatus enum.
func (e RunStatus) Valid() bool {
	switch e {
	case RunStatusCanceled:
		return true
	case RunStatusCanceling:
		return true
	case RunStatusCompleted:
		return true
	case RunStatusFailed:
		return true
	case RunStatusFailedRecoverable:
		return true
	case RunStatusQueued:
		return true
	case RunStatusRunning:
		return true
	case RunStatusWaitingForUser:
		return true
	default:
		return false
	}
}

// Defines values for RunUsageEntryKind.
const (
	ModelReservation RunUsageEntryKind = "model.reservation"
	ModelSettlement  RunUsageEntryKind = "model.settlement"
	ToolExecution    RunUsageEntryKind = "tool.execution"
)

// Valid indicates whether the value is a known member of the RunUsageEntryKind enum.
func (e RunUsageEntryKind) Valid() bool {
	switch e {
	case ModelReservation:
		return true
	case ModelSettlement:
		return true
	case ToolExecution:
		return true
	default:
		return false
	}
}

// Defines values for RunUsageEntryPurpose.
const (
	Compaction RunUsageEntryPurpose = "compaction"
	Primary    RunUsageEntryPurpose = "primary"
	Router     RunUsageEntryPurpose = "router"
)

// Valid indicates whether the value is a known member of the RunUsageEntryPurpose enum.
func (e RunUsageEntryPurpose) Valid() bool {
	switch e {
	case Compaction:
		return true
	case Primary:
		return true
	case Router:
		return true
	default:
		return false
	}
}

// Defines values for VerificationPolicyInputMode.
const (
	AllMustPass VerificationPolicyInputMode = "all_must_pass"
	AnyMayPass  VerificationPolicyInputMode = "any_may_pass"
)

// Valid indicates whether the value is a known member of the VerificationPolicyInputMode enum.
func (e VerificationPolicyInputMode) Valid() bool {
	switch e {
	case AllMustPass:
		return true
	case AnyMayPass:
		return true
	default:
		return false
	}
}

// Defines values for VerificationPolicyInputOnExhausted.
const (
	VerificationPolicyInputOnExhaustedFail           VerificationPolicyInputOnExhausted = "fail"
	VerificationPolicyInputOnExhaustedWaitingForUser VerificationPolicyInputOnExhausted = "waiting_for_user"
)

// Valid indicates whether the value is a known member of the VerificationPolicyInputOnExhausted enum.
func (e VerificationPolicyInputOnExhausted) Valid() bool {
	switch e {
	case VerificationPolicyInputOnExhaustedFail:
		return true
	case VerificationPolicyInputOnExhaustedWaitingForUser:
		return true
	default:
		return false
	}
}

// Defines values for VerificationStatus.
const (
	VerificationStatusBlocked     VerificationStatus = "blocked"
	VerificationStatusFailed      VerificationStatus = "failed"
	VerificationStatusNotRequired VerificationStatus = "not_required"
	VerificationStatusPassed      VerificationStatus = "passed"
	VerificationStatusPending     VerificationStatus = "pending"
	VerificationStatusRunning     VerificationStatus = "running"
	VerificationStatusStale       VerificationStatus = "stale"
)

// Valid indicates whether the value is a known member of the VerificationStatus enum.
func (e VerificationStatus) Valid() bool {
	switch e {
	case VerificationStatusBlocked:
		return true
	case VerificationStatusFailed:
		return true
	case VerificationStatusNotRequired:
		return true
	case VerificationStatusPassed:
		return true
	case VerificationStatusPending:
		return true
	case VerificationStatusRunning:
		return true
	case VerificationStatusStale:
		return true
	default:
		return false
	}
}

// Defines values for VerifierType.
const (
	Citation        VerifierType = "citation"
	Command         VerifierType = "command"
	Http            VerifierType = "http"
	JsonSchema      VerifierType = "json_schema"
	TextConstraints VerifierType = "text_constraints"
)

// Valid indicates whether the value is a known member of the VerifierType enum.
func (e VerifierType) Valid() bool {
	switch e {
	case Citation:
		return true
	case Command:
		return true
	case Http:
		return true
	case JsonSchema:
		return true
	case TextConstraints:
		return true
	default:
		return false
	}
}

// Agent defines model for Agent.
type Agent struct {
	Archived         *bool        `json:"archived,omitempty"`
	CreatedAt        time.Time    `json:"created_at"`
	Description      string       `json:"description"`
	Executor         ChatExecutor `json:"executor"`
	Id               string       `json:"id"`
	MemoryEnabled    bool         `json:"memory_enabled"`
	Name             string       `json:"name"`
	RetrievalEnabled bool         `json:"retrieval_enabled"`
	SystemPrompt     string       `json:"system_prompt"`
	Tools            []string     `json:"tools"`
	UpdatedAt        time.Time    `json:"updated_at"`
}

// AgentConfigRequest defines model for AgentConfigRequest.
type AgentConfigRequest struct {
	Description      *string       `json:"description,omitempty"`
	Executor         *ChatExecutor `json:"executor,omitempty"`
	Id               *string       `json:"id,omitempty"`
	MemoryEnabled    *bool         `json:"memory_enabled,omitempty"`
	Name             *string       `json:"name,omitempty"`
	RetrievalEnabled *bool         `json:"retrieval_enabled,omitempty"`
	SystemPrompt     *string       `json:"system_prompt,omitempty"`
	Tools            *[]string     `json:"tools,omitempty"`
}

// ChatExecutor defines model for ChatExecutor.
type ChatExecutor string

// ChatMode defines model for ChatMode.
type ChatMode string

// ChatRequest defines model for ChatRequest.
type ChatRequest struct {
	AgentId            *string                  `json:"agent_id,omitempty"`
	CompletionContract *CompletionContractInput `json:"completion_contract,omitempty"`
	ConversationId     *string                  `json:"conversation_id,omitempty"`
	Executor           *ChatExecutor            `json:"executor,omitempty"`
	Message            string                   `json:"message"`
	Mode               *ChatMode                `json:"mode,omitempty"`
}

// CollaborationStep defines model for CollaborationStep.
type CollaborationStep struct {
	AgentId        *string                 `json:"agent_id,omitempty"`
	ConversationId string                  `json:"conversation_id"`
	CreatedAt      time.Time               `json:"created_at"`
	Error          *string                 `json:"error,omitempty"`
	Id             string                  `json:"id"`
	Input          string                  `json:"input"`
	Iteration      *int                    `json:"iteration,omitempty"`
	Output         string                  `json:"output"`
	Role           string                  `json:"role"`
	RunId          string                  `json:"run_id"`
	Status         CollaborationStepStatus `json:"status"`
	UpdatedAt      time.Time               `json:"updated_at"`
}

// CollaborationStepStatus defines model for CollaborationStep.Status.
type CollaborationStepStatus string

// CompletionContract defines model for CompletionContract.
type CompletionContract struct {
	Hash        string                        `json:"hash"`
	Id          string                        `json:"id"`
	Policy      VerificationPolicyInput       `json:"policy"`
	SubjectType CompletionContractSubjectType `json:"subject_type"`
	Verifiers   []VerifierSpecInput           `json:"verifiers"`
	Version     int                           `json:"version"`
}

// CompletionContractSubjectType defines model for CompletionContract.SubjectType.
type CompletionContractSubjectType string

// CompletionContractInput defines model for CompletionContractInput.
type CompletionContractInput struct {
	Policy      VerificationPolicyInput            `json:"policy"`
	SubjectType CompletionContractInputSubjectType `json:"subject_type"`
	Verifiers   []VerifierSpecInput                `json:"verifiers"`
}

// CompletionContractInputSubjectType defines model for CompletionContractInput.SubjectType.
type CompletionContractInputSubjectType string

// ContinueRunRequest defines model for ContinueRunRequest.
type ContinueRunRequest struct {
	Plan string `json:"plan"`
}

// Conversation defines model for Conversation.
type Conversation struct {
	CreatedAt time.Time `json:"created_at"`
	Id        string    `json:"id"`
	Title     string    `json:"title"`
	UpdatedAt time.Time `json:"updated_at"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// Message defines model for Message.
type Message struct {
	Content        string      `json:"content"`
	ConversationId string      `json:"conversation_id"`
	CreatedAt      time.Time   `json:"created_at"`
	Id             string      `json:"id"`
	Role           MessageRole `json:"role"`
}

// MessageRole defines model for Message.Role.
type MessageRole string

// ResumeRunRequest defines model for ResumeRunRequest.
type ResumeRunRequest struct {
	UserInput string `json:"user_input"`
}

// Run defines model for Run.
type Run struct {
	ActiveRuntimeMs    int64               `json:"active_runtime_ms"`
	AgentId            string              `json:"agent_id"`
	CompletedAt        *time.Time          `json:"completed_at,omitempty"`
	CompletionContract *CompletionContract `json:"completion_contract,omitempty"`
	ConversationId     string              `json:"conversation_id"`
	CreatedAt          time.Time           `json:"created_at"`
	Error              *string             `json:"error,omitempty"`
	ExecutionStartedAt *time.Time          `json:"execution_started_at,omitempty"`
	HeartbeatAt        *time.Time          `json:"heartbeat_at,omitempty"`
	Id                 string              `json:"id"`
	StartedAt          *time.Time          `json:"started_at,omitempty"`
	Status             RunStatus           `json:"status"`
	UpdatedAt          time.Time           `json:"updated_at"`
	VerificationStatus VerificationStatus  `json:"verification_status"`
}

// RunEvent defines model for RunEvent.
type RunEvent struct {
	ConversationId *string                `json:"conversation_id,omitempty"`
	Id             string                 `json:"id"`
	ParentEventId  *string                `json:"parent_event_id,omitempty"`
	Payload        map[string]interface{} `json:"payload"`
	RunId          string                 `json:"run_id"`
	SchemaVersion  int                    `json:"schema_version"`
	Sequence       int64                  `json:"sequence"`
	StageId        *string                `json:"stage_id,omitempty"`
	Timestamp      time.Time              `json:"timestamp"`
	TurnId         *string                `json:"turn_id,omitempty"`
	Type           string                 `json:"type"`
}

// RunReplay defines model for RunReplay.
type RunReplay struct {
	Conversation          Conversation            `json:"conversation"`
	Messages              []Message               `json:"messages"`
	Run                   Run                     `json:"run"`
	RunEvents             []RunEvent              `json:"run_events"`
	RuntimeSnapshot       *map[string]interface{} `json:"runtime_snapshot,omitempty"`
	Steps                 []CollaborationStep     `json:"steps"`
	Summary               RunTraceSummary         `json:"summary"`
	UsageLedger           RunUsageLedger          `json:"usage_ledger"`
	VerificationArtifacts []VerificationArtifact  `json:"verification_artifacts"`
	VerificationEvidence  []VerificationEvidence  `json:"verification_evidence"`
}

// RunStatus defines model for RunStatus.
type RunStatus string

// RunTraceSummary defines model for RunTraceSummary.
type RunTraceSummary struct {
	CompletionTokens    int       `json:"completion_tokens"`
	ErrorCount          int       `json:"error_count"`
	LlmCalls            int       `json:"llm_calls"`
	PromptTokens        int       `json:"prompt_tokens"`
	RunId               string    `json:"run_id"`
	Status              RunStatus `json:"status"`
	TokenUsageEstimated bool      `json:"token_usage_estimated"`
	ToolCalls           int       `json:"tool_calls"`
	TotalDurationMs     int64     `json:"total_duration_ms"`
	TotalTokens         int       `json:"total_tokens"`
}

// RunUsageEntry defines model for RunUsageEntry.
type RunUsageEntry struct {
	CompletionTokens    *int                 `json:"completion_tokens,omitempty"`
	Estimated           *bool                `json:"estimated,omitempty"`
	EstimatedCostMicros *int64               `json:"estimated_cost_micros,omitempty"`
	Id                  string               `json:"id"`
	Kind                RunUsageEntryKind    `json:"kind"`
	Model               *string              `json:"model,omitempty"`
	ModelCalls          *int                 `json:"model_calls,omitempty"`
	OperationId         string               `json:"operation_id"`
	PromptTokens        *int                 `json:"prompt_tokens,omitempty"`
	Purpose             RunUsageEntryPurpose `json:"purpose"`
	RunId               string               `json:"run_id"`
	StageId             *string              `json:"stage_id,omitempty"`
	Timestamp           time.Time            `json:"timestamp"`
	ToolCalls           *int                 `json:"tool_calls,omitempty"`
	ToolName            *string              `json:"tool_name,omitempty"`
	TotalTokens         *int                 `json:"total_tokens,omitempty"`
	TurnId              *string              `json:"turn_id,omitempty"`
}

// RunUsageEntryKind defines model for RunUsageEntry.Kind.
type RunUsageEntryKind string

// RunUsageEntryPurpose defines model for RunUsageEntry.Purpose.
type RunUsageEntryPurpose string

// RunUsageLedger defines model for RunUsageLedger.
type RunUsageLedger struct {
	Budget    RuntimeRunBudget `json:"budget"`
	Entries   []RunUsageEntry  `json:"entries"`
	RunId     string           `json:"run_id"`
	Totals    RunUsageTotals   `json:"totals"`
	UpdatedAt *time.Time       `json:"updated_at,omitempty"`
}

// RunUsageTotals defines model for RunUsageTotals.
type RunUsageTotals struct {
	CompletionTokens    int   `json:"completion_tokens"`
	EstimatedCostMicros int64 `json:"estimated_cost_micros"`
	ModelCalls          int   `json:"model_calls"`
	OpenReservations    int   `json:"open_reservations"`
	PromptTokens        int   `json:"prompt_tokens"`
	ToolCalls           int   `json:"tool_calls"`
	TotalTokens         int   `json:"total_tokens"`
}

// RuntimeRunBudget defines model for RuntimeRunBudget.
type RuntimeRunBudget struct {
	InputCostPerMillionTokensMicros  *int64 `json:"input_cost_per_million_tokens_micros,omitempty"`
	MaxCompletionTokens              *int   `json:"max_completion_tokens,omitempty"`
	MaxEstimatedCostMicros           *int64 `json:"max_estimated_cost_micros,omitempty"`
	MaxModelCalls                    *int   `json:"max_model_calls,omitempty"`
	MaxPromptTokens                  *int   `json:"max_prompt_tokens,omitempty"`
	MaxRuntimeMs                     *int64 `json:"max_runtime_ms,omitempty"`
	MaxToolCalls                     *int   `json:"max_tool_calls,omitempty"`
	MaxTotalTokens                   *int   `json:"max_total_tokens,omitempty"`
	OutputCostPerMillionTokensMicros *int64 `json:"output_cost_per_million_tokens_micros,omitempty"`
}

// ToolInfo defines model for ToolInfo.
type ToolInfo struct {
	Description string                 `json:"description"`
	Enabled     bool                   `json:"enabled"`
	Name        string                 `json:"name"`
	Parameters  map[string]interface{} `json:"parameters"`
}

// VerificationArtifact defines model for VerificationArtifact.
type VerificationArtifact struct {
	EvidenceId           string                 `json:"evidence_id"`
	Id                   string                 `json:"id"`
	Kind                 string                 `json:"kind"`
	RunId                string                 `json:"run_id"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// VerificationDecision defines model for VerificationDecision.
type VerificationDecision struct {
	AllowCompletion bool               `json:"allow_completion"`
	Attempt         int                `json:"attempt"`
	RunStatus       RunStatus          `json:"run_status"`
	Status          VerificationStatus `json:"status"`
	SubjectHash     string             `json:"subject_hash"`
	Summary         string             `json:"summary"`
}

// VerificationEvidence defines model for VerificationEvidence.
type VerificationEvidence struct {
	Id                   string                 `json:"id"`
	RunId                string                 `json:"run_id"`
	Status               VerificationStatus     `json:"status"`
	VerifierId           string                 `json:"verifier_id"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// VerificationPolicyInput defines model for VerificationPolicyInput.
type VerificationPolicyInput struct {
	MaxAttempts int                                `json:"max_attempts"`
	Mode        VerificationPolicyInputMode        `json:"mode"`
	OnExhausted VerificationPolicyInputOnExhausted `json:"on_exhausted"`
}

// VerificationPolicyInputMode defines model for VerificationPolicyInput.Mode.
type VerificationPolicyInputMode string

// VerificationPolicyInputOnExhausted defines model for VerificationPolicyInput.OnExhausted.
type VerificationPolicyInputOnExhausted string

// VerificationStatus defines model for VerificationStatus.
type VerificationStatus string

// VerifierSpecInput defines model for VerifierSpecInput.
type VerifierSpecInput struct {
	Config    map[string]interface{} `json:"config"`
	Id        string                 `json:"id"`
	Required  bool                   `json:"required"`
	TimeoutMs *int64                 `json:"timeout_ms,omitempty"`
	Type      VerifierType           `json:"type"`
	Version   *string                `json:"version,omitempty"`
}

// VerifierType defines model for VerifierType.
type VerifierType string

// VerifyRunResponse defines model for VerifyRunResponse.
type VerifyRunResponse struct {
	Decision VerificationDecision `json:"decision"`
	Run      Run                  `json:"run"`
}

// AgentId defines model for AgentId.
type AgentId = string

// RunId defines model for RunId.
type RunId = string

// ToolName defines model for ToolName.
type ToolName = string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = ErrorResponse

// CreateAgentJSONRequestBody defines body for CreateAgent for application/json ContentType.
type CreateAgentJSONRequestBody = AgentConfigRequest

// UpdateAgentJSONRequestBody defines body for UpdateAgent for application/json ContentType.
type UpdateAgentJSONRequestBody = AgentConfigRequest

// StreamChatJSONRequestBody defines body for StreamChat for application/json ContentType.
type StreamChatJSONRequestBody = ChatRequest

// ContinueRunJSONRequestBody defines body for ContinueRun for application/json ContentType.
type ContinueRunJSONRequestBody = ContinueRunRequest

// ResumeRunJSONRequestBody defines body for ResumeRun for application/json ContentType.
type ResumeRunJSONRequestBody = ResumeRunRequest

// Getter for additional properties for VerificationArtifact. Returns the specified
// element and whether it was found
func (a VerificationArtifact) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for VerificationArtifact
func (a *VerificationArtifact) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for VerificationArtifact to handle AdditionalProperties
func (a *VerificationArtifact) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["evidence_id"]; found {
		err = json.Unmarshal(raw, &a.EvidenceId)
		if err != nil {
			return fmt.Errorf("error reading 'evidence_id': %w", err)
		}
		delete(object, "evidence_id")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["kind"]; found {
		err = json.Unmarshal(raw, &a.Kind)
		if err != nil {
			return fmt.Errorf("error reading 'kind': %w", err)
		}
		delete(object, "kind")
	}

	if raw, found := object["run_id"]; found {
		err = json.Unmarshal(raw, &a.RunId)
		if err != nil {
			return fmt.Errorf("error reading 'run_id': %w", err)
		}
		delete(object, "run_id")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for VerificationArtifact to handle AdditionalProperties
func (a VerificationArtifact) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["evidence_id"], err = json.Marshal(a.EvidenceId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'evidence_id': %w", err)
	}

	object["id"], err = json.Marshal(a.Id)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'id': %w", err)
	}

	object["kind"], err = json.Marshal(a.Kind)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'kind': %w", err)
	}

	object["run_id"], err = json.Marshal(a.RunId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'run_id': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for VerificationEvidence. Returns the specified
// element and whether it was found
func (a VerificationEvidence) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for VerificationEvidence
func (a *VerificationEvidence) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for VerificationEvidence to handle AdditionalProperties
func (a *VerificationEvidence) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["run_id"]; found {
		err = json.Unmarshal(raw, &a.RunId)
		if err != nil {
			return fmt.Errorf("error reading 'run_id': %w", err)
		}
		delete(object, "run_id")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["verifier_id"]; found {
		err = json.Unmarshal(raw, &a.VerifierId)
		if err != nil {
			return fmt.Errorf("error reading 'verifier_id': %w", err)
		}
		delete(object, "verifier_id")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for VerificationEvidence to handle AdditionalProperties
func (a VerificationEvidence) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["id"], err = json.Marshal(a.Id)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'id': %w", err)
	}

	object["run_id"], err = json.Marshal(a.RunId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'run_id': %w", err)
	}

	object["status"], err = json.Marshal(a.Status)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'status': %w", err)
	}

	object["verifier_id"], err = json.Marshal(a.VerifierId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'verifier_id': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
